/*
 * Native return-patch follow-up classifier.
 *
 * Generated by vm_native_ret_patch_followups_dump.c from dumps/vmtail-wide-1m-w16/vm_synthetic_gap_ret_patch_native_target_atlas.tsv.
 * This C-shaped evidence layer indexes the direct call/jump targets that
 * appear inside bounded native return-patch windows. It deliberately
 * distinguishes local epilogue branches, PLT/runtime calls, allocator
 * wrappers, internal helpers, and native obfuscation islands from VM CFG
 * successors.
 */
#include <stdint.h>

typedef struct VMState {
    uint8_t *ip;
    uint32_t state;
    uint32_t flags;
    uint8_t byte;
} VMState;

typedef struct VMNativeRetPatchFollowup {
    uint64_t source_entry;
    uint64_t synthetic_start_vm_ip;
    uint32_t patched_ret_eac_off;
    const char *edge_kind;
} VMNativeRetPatchFollowup;

static void vm_note_ret_patch_followup(VMState *vm, const VMNativeRetPatchFollowup *edge,
                                       uint32_t target, const char *classification,
                                       const char *priority) {
    (void)vm;
    (void)edge;
    (void)target;
    (void)classification;
    (void)priority;
}

static void followup_target_206c0(VMState *vm, const VMNativeRetPatchFollowup *edge) {
    /* target=0x206c0; section=.plt; class=plt_stack_chk_fail; priority=external_runtime */
    /* edge_count=12; edge_kind_mix=call:12; source_mix=entry_175:3,entry_195:6,entry_299:3 */
    /* relation_mix=outside_retpatch_window:12 */
    /* windows=175@0xd1445:0x217cb-0x2184b:1,175@0x17a420:0x31703-0x31783:1,175@0x1a6041:0x339bd-0x33a3d:1,195@0xd5ebc:0x21e1e-0x21e9e:1,195@0xdaf39:0x230d4-0x23154:1,195@0x1ed483:0x37af9-0x37b79:1,195@0x333bc9:0x748d8-0x74958:1,195@0x33d2d9:0x74f88-0x75008:1,195@0x3655e4:0x779bd-0x77a3d:1,299@0x122e3c:0x2d409-0x2d489:1,299@0x17452e:0x313eb-0x3146b:1,299@0x33710f:0x74b3d-0x74bbd:1 */
    /* note: __stack_chk_fail PLT target reached only from stack-cookie guard failure branches. */
    vm_note_ret_patch_followup(vm, edge, 0x206c0u, "plt_stack_chk_fail", "external_runtime");
}

static void followup_target_217ff(VMState *vm, const VMNativeRetPatchFollowup *edge) {
    /* target=0x217ff; section=.text; class=local_retpatch_window_branch; priority=covered_by_source_window */
    /* edge_count=1; edge_kind_mix=jump:1; source_mix=entry_175:1 */
    /* relation_mix=inside_retpatch_window:1 */
    /* windows=175@0xd1445:0x217cb-0x2184b:1 */
    /* note: Direct branch target stays inside an already-rendered native ret-patch disassembly window. */
    vm_note_ret_patch_followup(vm, edge, 0x217ffu, "local_retpatch_window_branch", "covered_by_source_window");
}

static void followup_target_21848(VMState *vm, const VMNativeRetPatchFollowup *edge) {
    /* target=0x21848; section=.text; class=local_retpatch_window_branch; priority=covered_by_source_window */
    /* edge_count=1; edge_kind_mix=jump:1; source_mix=entry_175:1 */
    /* relation_mix=inside_retpatch_window:1 */
    /* windows=175@0xd1445:0x217cb-0x2184b:1 */
    /* note: Direct branch target stays inside an already-rendered native ret-patch disassembly window. */
    vm_note_ret_patch_followup(vm, edge, 0x21848u, "local_retpatch_window_branch", "covered_by_source_window");
}

static void followup_target_21a50(VMState *vm, const VMNativeRetPatchFollowup *edge) {
    /* target=0x21a50; section=.text; class=internal_realloc_copy_helper; priority=targeted_retdec_candidate */
    /* edge_count=1; edge_kind_mix=call:1; source_mix=entry_175:1 */
    /* relation_mix=outside_retpatch_window:1 */
    /* windows=175@0xd1445:0x217cb-0x2184b:1 */
    /* note: Function-shaped helper with normal prologue; copies or reallocates buffered native state and calls allocator-family helpers. */
    vm_note_ret_patch_followup(vm, edge, 0x21a50u, "internal_realloc_copy_helper", "targeted_retdec_candidate");
}

static void followup_target_21e53(VMState *vm, const VMNativeRetPatchFollowup *edge) {
    /* target=0x21e53; section=.text; class=local_retpatch_window_branch; priority=covered_by_source_window */
    /* edge_count=1; edge_kind_mix=jump:1; source_mix=entry_195:1 */
    /* relation_mix=inside_retpatch_window:1 */
    /* windows=195@0xd5ebc:0x21e1e-0x21e9e:1 */
    /* note: Direct branch target stays inside an already-rendered native ret-patch disassembly window. */
    vm_note_ret_patch_followup(vm, edge, 0x21e53u, "local_retpatch_window_branch", "covered_by_source_window");
}

static void followup_target_23108(VMState *vm, const VMNativeRetPatchFollowup *edge) {
    /* target=0x23108; section=.text; class=local_retpatch_window_branch; priority=covered_by_source_window */
    /* edge_count=1; edge_kind_mix=jump:1; source_mix=entry_195:1 */
    /* relation_mix=inside_retpatch_window:1 */
    /* windows=195@0xdaf39:0x230d4-0x23154:1 */
    /* note: Direct branch target stays inside an already-rendered native ret-patch disassembly window. */
    vm_note_ret_patch_followup(vm, edge, 0x23108u, "local_retpatch_window_branch", "covered_by_source_window");
}

static void followup_target_23122(VMState *vm, const VMNativeRetPatchFollowup *edge) {
    /* target=0x23122; section=.text; class=internal_obfuscated_helper_to_e0017; priority=targeted_obfuscation_candidate */
    /* edge_count=1; edge_kind_mix=call:1; source_mix=entry_195:1 */
    /* relation_mix=inside_retpatch_window:1 */
    /* windows=195@0xdaf39:0x230d4-0x23154:1 */
    /* note: Function-shaped helper begins with a normal prologue then transfers into the 0xe0017 obfuscated native island. */
    vm_note_ret_patch_followup(vm, edge, 0x23122u, "internal_obfuscated_helper_to_e0017", "targeted_obfuscation_candidate");
}

static void followup_target_2508e(VMState *vm, const VMNativeRetPatchFollowup *edge) {
    /* target=0x2508e; section=.text; class=internal_container_wrapper; priority=bounded_targeted_retdec_candidate */
    /* edge_count=2; edge_kind_mix=call:2; source_mix=entry_195:2 */
    /* relation_mix=outside_retpatch_window:2 */
    /* windows=195@0x231b74:0x5f1c6-0x5f246:2 */
    /* note: Small wrapper around pointer adjustment and a tail transfer toward the nearby 0x24cb0 container/object helper family. */
    vm_note_ret_patch_followup(vm, edge, 0x2508eu, "internal_container_wrapper", "bounded_targeted_retdec_candidate");
}

static void followup_target_2d440(VMState *vm, const VMNativeRetPatchFollowup *edge) {
    /* target=0x2d440; section=.text; class=local_retpatch_window_branch; priority=covered_by_source_window */
    /* edge_count=1; edge_kind_mix=jump:1; source_mix=entry_299:1 */
    /* relation_mix=inside_retpatch_window:1 */
    /* windows=299@0x122e3c:0x2d409-0x2d489:1 */
    /* note: Direct branch target stays inside an already-rendered native ret-patch disassembly window. */
    vm_note_ret_patch_followup(vm, edge, 0x2d440u, "local_retpatch_window_branch", "covered_by_source_window");
}

static void followup_target_2d4c2(VMState *vm, const VMNativeRetPatchFollowup *edge) {
    /* target=0x2d4c2; section=.text; class=post_window_adjacent_branch; priority=covered_by_source_window */
    /* edge_count=1; edge_kind_mix=jump:1; source_mix=entry_299:1 */
    /* relation_mix=post_window_adjacent:1 */
    /* windows=299@0x122e3c:0x2d409-0x2d489:1 */
    /* note: Direct branch lands just after the bounded window; keep with the local native epilogue/adjacent-helper evidence. */
    vm_note_ret_patch_followup(vm, edge, 0x2d4c2u, "post_window_adjacent_branch", "covered_by_source_window");
}

static void followup_target_31422(VMState *vm, const VMNativeRetPatchFollowup *edge) {
    /* target=0x31422; section=.text; class=local_retpatch_window_branch; priority=covered_by_source_window */
    /* edge_count=1; edge_kind_mix=jump:1; source_mix=entry_299:1 */
    /* relation_mix=inside_retpatch_window:1 */
    /* windows=299@0x17452e:0x313eb-0x3146b:1 */
    /* note: Direct branch target stays inside an already-rendered native ret-patch disassembly window. */
    vm_note_ret_patch_followup(vm, edge, 0x31422u, "local_retpatch_window_branch", "covered_by_source_window");
}

static void followup_target_31739(VMState *vm, const VMNativeRetPatchFollowup *edge) {
    /* target=0x31739; section=.text; class=local_retpatch_window_branch; priority=covered_by_source_window */
    /* edge_count=1; edge_kind_mix=jump:1; source_mix=entry_175:1 */
    /* relation_mix=inside_retpatch_window:1 */
    /* windows=175@0x17a420:0x31703-0x31783:1 */
    /* note: Direct branch target stays inside an already-rendered native ret-patch disassembly window. */
    vm_note_ret_patch_followup(vm, edge, 0x31739u, "local_retpatch_window_branch", "covered_by_source_window");
}

static void followup_target_339f0(VMState *vm, const VMNativeRetPatchFollowup *edge) {
    /* target=0x339f0; section=.text; class=local_retpatch_window_branch; priority=covered_by_source_window */
    /* edge_count=1; edge_kind_mix=jump:1; source_mix=entry_175:1 */
    /* relation_mix=inside_retpatch_window:1 */
    /* windows=175@0x1a6041:0x339bd-0x33a3d:1 */
    /* note: Direct branch target stays inside an already-rendered native ret-patch disassembly window. */
    vm_note_ret_patch_followup(vm, edge, 0x339f0u, "local_retpatch_window_branch", "covered_by_source_window");
}

static void followup_target_37b2f(VMState *vm, const VMNativeRetPatchFollowup *edge) {
    /* target=0x37b2f; section=.text; class=local_retpatch_window_branch; priority=covered_by_source_window */
    /* edge_count=1; edge_kind_mix=jump:1; source_mix=entry_195:1 */
    /* relation_mix=inside_retpatch_window:1 */
    /* windows=195@0x1ed483:0x37af9-0x37b79:1 */
    /* note: Direct branch target stays inside an already-rendered native ret-patch disassembly window. */
    vm_note_ret_patch_followup(vm, edge, 0x37b2fu, "local_retpatch_window_branch", "covered_by_source_window");
}

static void followup_target_5f221(VMState *vm, const VMNativeRetPatchFollowup *edge) {
    /* target=0x5f221; section=.text; class=local_retpatch_window_branch; priority=covered_by_source_window */
    /* edge_count=1; edge_kind_mix=jump:1; source_mix=entry_195:1 */
    /* relation_mix=inside_retpatch_window:1 */
    /* windows=195@0x231b74:0x5f1c6-0x5f246:1 */
    /* note: Direct branch target stays inside an already-rendered native ret-patch disassembly window. */
    vm_note_ret_patch_followup(vm, edge, 0x5f221u, "local_retpatch_window_branch", "covered_by_source_window");
}

static void followup_target_5f23d(VMState *vm, const VMNativeRetPatchFollowup *edge) {
    /* target=0x5f23d; section=.text; class=local_retpatch_window_branch; priority=covered_by_source_window */
    /* edge_count=1; edge_kind_mix=jump:1; source_mix=entry_195:1 */
    /* relation_mix=inside_retpatch_window:1 */
    /* windows=195@0x231b74:0x5f1c6-0x5f246:1 */
    /* note: Direct branch target stays inside an already-rendered native ret-patch disassembly window. */
    vm_note_ret_patch_followup(vm, edge, 0x5f23du, "local_retpatch_window_branch", "covered_by_source_window");
}

static void followup_target_5f24b(VMState *vm, const VMNativeRetPatchFollowup *edge) {
    /* target=0x5f24b; section=.text; class=post_window_adjacent_branch; priority=covered_by_source_window */
    /* edge_count=1; edge_kind_mix=jump:1; source_mix=entry_195:1 */
    /* relation_mix=post_window_adjacent:1 */
    /* windows=195@0x231b74:0x5f1c6-0x5f246:1 */
    /* note: Direct branch lands just after the bounded window; keep with the local native epilogue/adjacent-helper evidence. */
    vm_note_ret_patch_followup(vm, edge, 0x5f24bu, "post_window_adjacent_branch", "covered_by_source_window");
}

static void followup_target_5f259(VMState *vm, const VMNativeRetPatchFollowup *edge) {
    /* target=0x5f259; section=.text; class=post_window_adjacent_branch; priority=covered_by_source_window */
    /* edge_count=1; edge_kind_mix=jump:1; source_mix=entry_195:1 */
    /* relation_mix=post_window_adjacent:1 */
    /* windows=195@0x231b74:0x5f1c6-0x5f246:1 */
    /* note: Direct branch lands just after the bounded window; keep with the local native epilogue/adjacent-helper evidence. */
    vm_note_ret_patch_followup(vm, edge, 0x5f259u, "post_window_adjacent_branch", "covered_by_source_window");
}

static void followup_target_6c064(VMState *vm, const VMNativeRetPatchFollowup *edge) {
    /* target=0x6c064; section=.text; class=local_retpatch_window_branch; priority=covered_by_source_window */
    /* edge_count=1; edge_kind_mix=jump:1; source_mix=entry_278:1 */
    /* relation_mix=inside_retpatch_window:1 */
    /* windows=278@0x12906f:0x6c010-0x6c090:1 */
    /* note: Direct branch target stays inside an already-rendered native ret-patch disassembly window. */
    vm_note_ret_patch_followup(vm, edge, 0x6c064u, "local_retpatch_window_branch", "covered_by_source_window");
}

static void followup_target_6c0be(VMState *vm, const VMNativeRetPatchFollowup *edge) {
    /* target=0x6c0be; section=.text; class=post_window_adjacent_branch; priority=covered_by_source_window */
    /* edge_count=1; edge_kind_mix=jump:1; source_mix=entry_278:1 */
    /* relation_mix=post_window_adjacent:1 */
    /* windows=278@0x12906f:0x6c010-0x6c090:1 */
    /* note: Direct branch lands just after the bounded window; keep with the local native epilogue/adjacent-helper evidence. */
    vm_note_ret_patch_followup(vm, edge, 0x6c0beu, "post_window_adjacent_branch", "covered_by_source_window");
}

static void followup_target_7260a(VMState *vm, const VMNativeRetPatchFollowup *edge) {
    /* target=0x7260a; section=.text; class=internal_helper_chain; priority=bounded_targeted_retdec_candidate */
    /* edge_count=1; edge_kind_mix=jump:1; source_mix=entry_195:1 */
    /* relation_mix=outside_retpatch_window:1 */
    /* windows=195@0x1ed483:0x37af9-0x37b79:1 */
    /* note: Small helper calls the nearby 0x72588 routine and tail-transfers onward; it is native control, not a VM dispatch edge. */
    vm_note_ret_patch_followup(vm, edge, 0x7260au, "internal_helper_chain", "bounded_targeted_retdec_candidate");
}

static void followup_target_729b6(VMState *vm, const VMNativeRetPatchFollowup *edge) {
    /* target=0x729b6; section=.text; class=pthread_mutex_lock_store_helper; priority=native_semantics_recovered */
    /* edge_count=1; edge_kind_mix=call:1; source_mix=entry_299:1 */
    /* relation_mix=outside_retpatch_window:1 */
    /* windows=299@0x122e3c:0x2d409-0x2d489:1 */
    /* note: Tiny helper stores rsi through rdi, moves rsi to rdi, then tail-jumps to pthread_mutex_lock@plt. */
    vm_note_ret_patch_followup(vm, edge, 0x729b6u, "pthread_mutex_lock_store_helper", "native_semantics_recovered");
}

static void followup_target_74910(VMState *vm, const VMNativeRetPatchFollowup *edge) {
    /* target=0x74910; section=.text; class=local_retpatch_window_branch; priority=covered_by_source_window */
    /* edge_count=1; edge_kind_mix=jump:1; source_mix=entry_195:1 */
    /* relation_mix=inside_retpatch_window:1 */
    /* windows=195@0x333bc9:0x748d8-0x74958:1 */
    /* note: Direct branch target stays inside an already-rendered native ret-patch disassembly window. */
    vm_note_ret_patch_followup(vm, edge, 0x74910u, "local_retpatch_window_branch", "covered_by_source_window");
}

static void followup_target_74b75(VMState *vm, const VMNativeRetPatchFollowup *edge) {
    /* target=0x74b75; section=.text; class=local_retpatch_window_branch; priority=covered_by_source_window */
    /* edge_count=1; edge_kind_mix=jump:1; source_mix=entry_299:1 */
    /* relation_mix=inside_retpatch_window:1 */
    /* windows=299@0x33710f:0x74b3d-0x74bbd:1 */
    /* note: Direct branch target stays inside an already-rendered native ret-patch disassembly window. */
    vm_note_ret_patch_followup(vm, edge, 0x74b75u, "local_retpatch_window_branch", "covered_by_source_window");
}

static void followup_target_74c0e(VMState *vm, const VMNativeRetPatchFollowup *edge) {
    /* target=0x74c0e; section=.text; class=post_window_adjacent_branch; priority=covered_by_source_window */
    /* edge_count=1; edge_kind_mix=jump:1; source_mix=entry_299:1 */
    /* relation_mix=post_window_adjacent:1 */
    /* windows=299@0x33710f:0x74b3d-0x74bbd:1 */
    /* note: Direct branch lands just after the bounded window; keep with the local native epilogue/adjacent-helper evidence. */
    vm_note_ret_patch_followup(vm, edge, 0x74c0eu, "post_window_adjacent_branch", "covered_by_source_window");
}

static void followup_target_74fbd(VMState *vm, const VMNativeRetPatchFollowup *edge) {
    /* target=0x74fbd; section=.text; class=local_retpatch_window_branch; priority=covered_by_source_window */
    /* edge_count=1; edge_kind_mix=jump:1; source_mix=entry_195:1 */
    /* relation_mix=inside_retpatch_window:1 */
    /* windows=195@0x33d2d9:0x74f88-0x75008:1 */
    /* note: Direct branch target stays inside an already-rendered native ret-patch disassembly window. */
    vm_note_ret_patch_followup(vm, edge, 0x74fbdu, "local_retpatch_window_branch", "covered_by_source_window");
}

static void followup_target_779f3(VMState *vm, const VMNativeRetPatchFollowup *edge) {
    /* target=0x779f3; section=.text; class=local_retpatch_window_branch; priority=covered_by_source_window */
    /* edge_count=1; edge_kind_mix=jump:1; source_mix=entry_195:1 */
    /* relation_mix=inside_retpatch_window:1 */
    /* windows=195@0x3655e4:0x779bd-0x77a3d:1 */
    /* note: Direct branch target stays inside an already-rendered native ret-patch disassembly window. */
    vm_note_ret_patch_followup(vm, edge, 0x779f3u, "local_retpatch_window_branch", "covered_by_source_window");
}

static void followup_target_77a5d(VMState *vm, const VMNativeRetPatchFollowup *edge) {
    /* target=0x77a5d; section=.text; class=post_window_adjacent_branch; priority=covered_by_source_window */
    /* edge_count=1; edge_kind_mix=jump:1; source_mix=entry_195:1 */
    /* relation_mix=post_window_adjacent:1 */
    /* windows=195@0x3655e4:0x779bd-0x77a3d:1 */
    /* note: Direct branch lands just after the bounded window; keep with the local native epilogue/adjacent-helper evidence. */
    vm_note_ret_patch_followup(vm, edge, 0x77a5du, "post_window_adjacent_branch", "covered_by_source_window");
}

static void followup_target_e0017(VMState *vm, const VMNativeRetPatchFollowup *edge) {
    /* target=0xe0017; section=.text; class=obfuscated_native_island; priority=obfuscation_island_candidate */
    /* edge_count=1; edge_kind_mix=jump:1; source_mix=entry_195:1 */
    /* relation_mix=outside_retpatch_window:1 */
    /* windows=195@0xdaf39:0x230d4-0x23154:1 */
    /* note: Native obfuscation island with flag/stack gymnastics; reached from the 0x23122 helper path. */
    vm_note_ret_patch_followup(vm, edge, 0xe0017u, "obfuscated_native_island", "obfuscation_island_candidate");
}

static void followup_target_17bf1f(VMState *vm, const VMNativeRetPatchFollowup *edge) {
    /* target=0x17bf1f; section=.text; class=obfuscated_native_island; priority=obfuscation_island_candidate */
    /* edge_count=1; edge_kind_mix=jump:1; source_mix=entry_299:1 */
    /* relation_mix=outside_retpatch_window:1 */
    /* windows=299@0x17452e:0x313eb-0x3146b:1 */
    /* note: Native obfuscation island reached by source 299 ret-patch follow-up control. */
    vm_note_ret_patch_followup(vm, edge, 0x17bf1fu, "obfuscated_native_island", "obfuscation_island_candidate");
}

static void followup_target_231586(VMState *vm, const VMNativeRetPatchFollowup *edge) {
    /* target=0x231586; section=.text; class=obfuscated_native_island; priority=obfuscation_island_candidate */
    /* edge_count=1; edge_kind_mix=jump:1; source_mix=entry_195:1 */
    /* relation_mix=outside_retpatch_window:1 */
    /* windows=195@0x2304b8:0x44d7b-0x44dfb:1 */
    /* note: Native obfuscation island reached by a source 195 ret-patch target window. */
    vm_note_ret_patch_followup(vm, edge, 0x231586u, "obfuscated_native_island", "obfuscation_island_candidate");
}

static void followup_target_2d2cf4(VMState *vm, const VMNativeRetPatchFollowup *edge) {
    /* target=0x2d2cf4; section=.text; class=source278_downstream_retdec_covered; priority=covered_by_source278_retdec */
    /* edge_count=1; edge_kind_mix=jump:1; source_mix=entry_278:1 */
    /* relation_mix=outside_retpatch_window:1 */
    /* windows=278@0x12906f:0x6c010-0x6c090:1 */
    /* note: Downstream native target already represented in the source278 targeted RetDec sidecar. */
    vm_note_ret_patch_followup(vm, edge, 0x2d2cf4u, "source278_downstream_retdec_covered", "covered_by_source278_retdec");
}

static void followup_target_337d35(VMState *vm, const VMNativeRetPatchFollowup *edge) {
    /* target=0x337d35; section=.text; class=obfuscated_native_island; priority=obfuscation_island_candidate */
    /* edge_count=1; edge_kind_mix=jump:1; source_mix=entry_195:1 */
    /* relation_mix=outside_retpatch_window:1 */
    /* windows=195@0x333bc9:0x748d8-0x74958:1 */
    /* note: Native obfuscation island reached by a source 195 ret-patch target window. */
    vm_note_ret_patch_followup(vm, edge, 0x337d35u, "obfuscated_native_island", "obfuscation_island_candidate");
}

static void followup_target_33b4b6(VMState *vm, const VMNativeRetPatchFollowup *edge) {
    /* target=0x33b4b6; section=.text; class=obfuscated_native_island; priority=obfuscation_island_candidate */
    /* edge_count=1; edge_kind_mix=jump:1; source_mix=entry_299:1 */
    /* relation_mix=outside_retpatch_window:1 */
    /* windows=299@0x33710f:0x74b3d-0x74bbd:1 */
    /* note: Native obfuscation island reached by source 299 ret-patch follow-up control. */
    vm_note_ret_patch_followup(vm, edge, 0x33b4b6u, "obfuscated_native_island", "obfuscation_island_candidate");
}

static void followup_target_33f109(VMState *vm, const VMNativeRetPatchFollowup *edge) {
    /* target=0x33f109; section=.text; class=obfuscated_native_island; priority=obfuscation_island_candidate */
    /* edge_count=1; edge_kind_mix=jump:1; source_mix=entry_195:1 */
    /* relation_mix=outside_retpatch_window:1 */
    /* windows=195@0x33d2d9:0x74f88-0x75008:1 */
    /* note: Native obfuscation island reached by a source 195 ret-patch target window. */
    vm_note_ret_patch_followup(vm, edge, 0x33f109u, "obfuscated_native_island", "obfuscation_island_candidate");
}

static void followup_target_36afd2(VMState *vm, const VMNativeRetPatchFollowup *edge) {
    /* target=0x36afd2; section=.text; class=obfuscated_native_island; priority=obfuscation_island_candidate */
    /* edge_count=1; edge_kind_mix=jump:1; source_mix=entry_195:1 */
    /* relation_mix=outside_retpatch_window:1 */
    /* windows=195@0x3655e4:0x779bd-0x77a3d:1 */
    /* note: Native obfuscation island reached by a source 195 ret-patch target window. */
    vm_note_ret_patch_followup(vm, edge, 0x36afd2u, "obfuscated_native_island", "obfuscation_island_candidate");
}

static void followup_target_48eb2b(VMState *vm, const VMNativeRetPatchFollowup *edge) {
    /* target=0x48eb2b; section=.text; class=internal_large_string_state_helper; priority=targeted_retdec_candidate */
    /* edge_count=1; edge_kind_mix=call:1; source_mix=entry_175:1 */
    /* relation_mix=outside_retpatch_window:1 */
    /* windows=175@0x17a420:0x31703-0x31783:1 */
    /* note: Large function-shaped helper with string references and allocator/helper calls; worth a narrow decompiler pass, not a broad sweep. */
    vm_note_ret_patch_followup(vm, edge, 0x48eb2bu, "internal_large_string_state_helper", "targeted_retdec_candidate");
}

static void followup_target_4eeb30(VMState *vm, const VMNativeRetPatchFollowup *edge) {
    /* target=0x4eeb30; section=.text; class=allocator_free_wrapper; priority=native_semantics_recovered */
    /* edge_count=1; edge_kind_mix=jump:1; source_mix=entry_195:1 */
    /* relation_mix=outside_retpatch_window:1 */
    /* windows=195@0x231b74:0x5f1c6-0x5f246:1 */
    /* note: Allocator/free wrapper family target; observed as native cleanup control rather than bytecode CFG. */
    vm_note_ret_patch_followup(vm, edge, 0x4eeb30u, "allocator_free_wrapper", "native_semantics_recovered");
}

static void followup_target_4eeb50(VMState *vm, const VMNativeRetPatchFollowup *edge) {
    /* target=0x4eeb50; section=.text; class=allocator_free_wrapper; priority=native_semantics_recovered */
    /* edge_count=1; edge_kind_mix=jump:1; source_mix=entry_195:1 */
    /* relation_mix=outside_retpatch_window:1 */
    /* windows=195@0x231b74:0x5f1c6-0x5f246:1 */
    /* note: Allocator/free wrapper family target; observed as native cleanup control rather than bytecode CFG. */
    vm_note_ret_patch_followup(vm, edge, 0x4eeb50u, "allocator_free_wrapper", "native_semantics_recovered");
}

void vm_native_ret_patch_followup(VMState *vm, uint32_t target,
                                  const VMNativeRetPatchFollowup *edge) {
    switch (target) {
    case 0x206c0u:
        followup_target_206c0(vm, edge);
        break;
    case 0x217ffu:
        followup_target_217ff(vm, edge);
        break;
    case 0x21848u:
        followup_target_21848(vm, edge);
        break;
    case 0x21a50u:
        followup_target_21a50(vm, edge);
        break;
    case 0x21e53u:
        followup_target_21e53(vm, edge);
        break;
    case 0x23108u:
        followup_target_23108(vm, edge);
        break;
    case 0x23122u:
        followup_target_23122(vm, edge);
        break;
    case 0x2508eu:
        followup_target_2508e(vm, edge);
        break;
    case 0x2d440u:
        followup_target_2d440(vm, edge);
        break;
    case 0x2d4c2u:
        followup_target_2d4c2(vm, edge);
        break;
    case 0x31422u:
        followup_target_31422(vm, edge);
        break;
    case 0x31739u:
        followup_target_31739(vm, edge);
        break;
    case 0x339f0u:
        followup_target_339f0(vm, edge);
        break;
    case 0x37b2fu:
        followup_target_37b2f(vm, edge);
        break;
    case 0x5f221u:
        followup_target_5f221(vm, edge);
        break;
    case 0x5f23du:
        followup_target_5f23d(vm, edge);
        break;
    case 0x5f24bu:
        followup_target_5f24b(vm, edge);
        break;
    case 0x5f259u:
        followup_target_5f259(vm, edge);
        break;
    case 0x6c064u:
        followup_target_6c064(vm, edge);
        break;
    case 0x6c0beu:
        followup_target_6c0be(vm, edge);
        break;
    case 0x7260au:
        followup_target_7260a(vm, edge);
        break;
    case 0x729b6u:
        followup_target_729b6(vm, edge);
        break;
    case 0x74910u:
        followup_target_74910(vm, edge);
        break;
    case 0x74b75u:
        followup_target_74b75(vm, edge);
        break;
    case 0x74c0eu:
        followup_target_74c0e(vm, edge);
        break;
    case 0x74fbdu:
        followup_target_74fbd(vm, edge);
        break;
    case 0x779f3u:
        followup_target_779f3(vm, edge);
        break;
    case 0x77a5du:
        followup_target_77a5d(vm, edge);
        break;
    case 0xe0017u:
        followup_target_e0017(vm, edge);
        break;
    case 0x17bf1fu:
        followup_target_17bf1f(vm, edge);
        break;
    case 0x231586u:
        followup_target_231586(vm, edge);
        break;
    case 0x2d2cf4u:
        followup_target_2d2cf4(vm, edge);
        break;
    case 0x337d35u:
        followup_target_337d35(vm, edge);
        break;
    case 0x33b4b6u:
        followup_target_33b4b6(vm, edge);
        break;
    case 0x33f109u:
        followup_target_33f109(vm, edge);
        break;
    case 0x36afd2u:
        followup_target_36afd2(vm, edge);
        break;
    case 0x48eb2bu:
        followup_target_48eb2b(vm, edge);
        break;
    case 0x4eeb30u:
        followup_target_4eeb30(vm, edge);
        break;
    case 0x4eeb50u:
        followup_target_4eeb50(vm, edge);
        break;
    default:
        vm_note_ret_patch_followup(vm, edge, target, "unknown_followup", "needs_static_audit");
        break;
    }
}
