/*
 * Native obfuscated second-stage stack-source proof.
 *
 * Generated by vm_native_obfuscated_second_stage_stack_source_dump.c.
 * Capstone validates the static stack source for the rbx dispatch index.
 */
#include <stdint.h>

typedef struct VMState { uint64_t dispatch_table_base; } VMState;

typedef struct VMSecondStageStackSource {
    const uint64_t *qwords;
    uint32_t qword_count;
} VMSecondStageStackSource;

static uint64_t vm_second_stage_stack_qword(const VMSecondStageStackSource *edge, uint32_t byte_off) {
    uint32_t index = byte_off >> 3;
    if (!edge || !edge->qwords || index >= edge->qword_count) {
        return 0;
    }
    return edge->qwords[index];
}

static void vm_note_second_stage_stack_source(VMState *vm, const VMSecondStageStackSource *edge,
                                              uint32_t entry, uint32_t site,
                                              uint64_t handler_entry, uint64_t dispatch_index,
                                              const char *load_kind, const char *status) {
    (void)vm;
    (void)edge;
    (void)entry;
    (void)site;
    (void)handler_entry;
    (void)dispatch_index;
    (void)load_kind;
    (void)status;
}

static void second_stage_stack_source_cad88(VMState *vm, const VMSecondStageStackSource *edge) {
    uint64_t handler_entry = vm_second_stage_stack_qword(edge, 0x88u);
    uint64_t dispatch_index = handler_entry << 3;
    /* entry=0xc9849; site=0xcad88; chain=source299_chain_a */
    /* source_push_site=0xcaca3; load_site=0xcacb0; shift_site=0xcacf1; load_kind=mov_rbx_qword_rsp; duplicate_pushes=2; preserved_rbx_writes=1 */
    vm_note_second_stage_stack_source(vm, edge, 0xc9849u, 0xcad88u, handler_entry,
                                      dispatch_index, "mov_rbx_qword_rsp", "static_stack_source_to_rbx_shift_proven");
}

static void second_stage_stack_source_cc3f5(VMState *vm, const VMSecondStageStackSource *edge) {
    uint64_t handler_entry = vm_second_stage_stack_qword(edge, 0x88u);
    uint64_t dispatch_index = handler_entry << 3;
    /* entry=0xcaf2a; site=0xcc3f5; chain=source195_chain_b */
    /* source_push_site=0xcc31c; load_site=0xcc326; shift_site=0xcc36a; load_kind=mov_rbx_qword_rsp; duplicate_pushes=1; preserved_rbx_writes=0 */
    vm_note_second_stage_stack_source(vm, edge, 0xcaf2au, 0xcc3f5u, handler_entry,
                                      dispatch_index, "mov_rbx_qword_rsp", "static_stack_source_to_rbx_shift_proven");
}

static void second_stage_stack_source_c559d(VMState *vm, const VMSecondStageStackSource *edge) {
    uint64_t handler_entry = vm_second_stage_stack_qword(edge, 0x88u);
    uint64_t dispatch_index = handler_entry << 3;
    /* entry=0xc4258; site=0xc559d; chain=source299_chain_b */
    /* source_push_site=0xc54c6; load_site=0xc54d3; shift_site=0xc5512; load_kind=mov_rbx_qword_rsp; duplicate_pushes=2; preserved_rbx_writes=0 */
    vm_note_second_stage_stack_source(vm, edge, 0xc4258u, 0xc559du, handler_entry,
                                      dispatch_index, "mov_rbx_qword_rsp", "static_stack_source_to_rbx_shift_proven");
}

static void second_stage_stack_source_c6bce(VMState *vm, const VMSecondStageStackSource *edge) {
    uint64_t handler_entry = vm_second_stage_stack_qword(edge, 0x88u);
    uint64_t dispatch_index = handler_entry << 3;
    /* entry=0xc57b8; site=0xc6bce; chain=source195_chain_c */
    /* source_push_site=0xc6afc; load_site=0xc6b09; shift_site=0xc6b43; load_kind=pop_rbx; duplicate_pushes=2; preserved_rbx_writes=0 */
    vm_note_second_stage_stack_source(vm, edge, 0xc57b8u, 0xc6bceu, handler_entry,
                                      dispatch_index, "pop_rbx", "static_stack_source_to_rbx_shift_proven");
}

static void second_stage_stack_source_c80b9(VMState *vm, const VMSecondStageStackSource *edge) {
    uint64_t handler_entry = vm_second_stage_stack_qword(edge, 0x88u);
    uint64_t dispatch_index = handler_entry << 3;
    /* entry=0xc6d58; site=0xc80b9; chain=source195_chain_d */
    /* source_push_site=0xc7fdc; load_site=0xc7fe6; shift_site=0xc802e; load_kind=mov_rbx_qword_rsp; duplicate_pushes=1; preserved_rbx_writes=0 */
    vm_note_second_stage_stack_source(vm, edge, 0xc6d58u, 0xc80b9u, handler_entry,
                                      dispatch_index, "mov_rbx_qword_rsp", "static_stack_source_to_rbx_shift_proven");
}

void vm_native_obfuscated_second_stage_stack_source(VMState *vm, uint32_t indirect_jmp_site,
                                                    const VMSecondStageStackSource *edge) {
    switch (indirect_jmp_site) {
    case 0xcad88u:
        second_stage_stack_source_cad88(vm, edge);
        break;
    case 0xcc3f5u:
        second_stage_stack_source_cc3f5(vm, edge);
        break;
    case 0xc559du:
        second_stage_stack_source_c559d(vm, edge);
        break;
    case 0xc6bceu:
        second_stage_stack_source_c6bce(vm, edge);
        break;
    case 0xc80b9u:
        second_stage_stack_source_c80b9(vm, edge);
        break;
    default:
        vm_note_second_stage_stack_source(vm, edge, 0, indirect_jmp_site, 0, 0,
                                             "-", "unknown_second_stage_stack_source_site");
        break;
    }
}
