/*
 * Native obfuscated second-stage computed-thunk map.
 *
 * Generated by vm_native_obfuscated_second_stage_dump.c from dumps/vmtail-wide-1m-w16/vm_native_obfuscated_islands.tsv.
 * These are the first-stage island downstreams that no longer end in a
 * direct jump. They reach computed jmp [rax] sites, so this artifact keeps
 * the C-shaped evidence precise and marks the remaining target recovery as
 * an instrumentation/symbolic-stack task.
 */
#include <stdint.h>

typedef struct VMState {
    uint8_t *ip;
    uint32_t state;
    uint32_t flags;
    uint8_t byte;
} VMState;

typedef struct VMNativeSecondStageThunk {
    uint64_t first_stage_entry;
    uint64_t synthetic_start_vm_ip;
    uint32_t native_entry;
    const char *source_mix;
} VMNativeSecondStageThunk;

static void vm_note_second_stage_thunk(VMState *vm, const VMNativeSecondStageThunk *edge,
                                       uint32_t entry, uint32_t computed_jump,
                                       const char *status, const char *next_action) {
    (void)vm;
    (void)edge;
    (void)entry;
    (void)computed_jump;
    (void)status;
    (void)next_action;
}

static void second_stage_thunk_c9849(VMState *vm, const VMNativeSecondStageThunk *edge) {
    /* entry=0xc9849; scan=0xc9849-0xcad8a; setup_call_target=0xc984e */
    /* loops: 0xca175->0xca166 and 0xcab3a->0xca97b; computed_jump=0xcad88 jmp [rax] */
    /* shape=call_plus_zero_stack_setup_two_internal_loops_computed_jmp_mem_rax; status=computed_indirect_target_unresolved; next_action=instrument_or_symbolically_collapse_jmp_rax_memory_target; next_linear_entry=0xcaf2a */
    /* first_stage_entries=0x17bf1f; source_mix=entry_299:1; first_stage_windows=299@0x17452e:0x313eb-0x3146b:1 */
    /* note: Reached from first-stage island 0x17bf1f; reaches a computed jmp [rax] rather than a direct downstream branch. */
    vm_note_second_stage_thunk(vm, edge, 0xc9849u, 0xcad88u, "computed_indirect_target_unresolved", "instrument_or_symbolically_collapse_jmp_rax_memory_target");
}

static void second_stage_thunk_caf2a(VMState *vm, const VMNativeSecondStageThunk *edge) {
    /* entry=0xcaf2a; scan=0xcaf2a-0xcc3f7; setup_call_target=0xcaf2f */
    /* loops: 0xcb941->0xcb932 and 0xcc23f->0xcc081; computed_jump=0xcc3f5 jmp [rax] */
    /* shape=call_plus_zero_stack_setup_two_internal_loops_computed_jmp_mem_rax; status=computed_indirect_target_unresolved; next_action=instrument_or_symbolically_collapse_jmp_rax_memory_target; next_linear_entry=0xcc59c */
    /* first_stage_entries=0x33f109; source_mix=entry_195:1; first_stage_windows=195@0x33d2d9:0x74f88-0x75008:1 */
    /* note: Reached from first-stage island 0x33f109; exact indirect target at jmp [rax] still needs native stack/register symbolic collapse. */
    vm_note_second_stage_thunk(vm, edge, 0xcaf2au, 0xcc3f5u, "computed_indirect_target_unresolved", "instrument_or_symbolically_collapse_jmp_rax_memory_target");
}

static void second_stage_thunk_c4258(VMState *vm, const VMNativeSecondStageThunk *edge) {
    /* entry=0xc4258; scan=0xc4258-0xc559f; setup_call_target=0xc425d */
    /* loops: 0xc4af1->0xc4ae2 and 0xc53a0->0xc524c; computed_jump=0xc559d jmp [rax] */
    /* shape=call_plus_zero_stack_setup_two_internal_loops_computed_jmp_mem_rax; status=computed_indirect_target_unresolved; next_action=instrument_or_symbolically_collapse_jmp_rax_memory_target; next_linear_entry=0xc57b8 */
    /* first_stage_entries=0x33b4b6; source_mix=entry_299:1; first_stage_windows=299@0x33710f:0x74b3d-0x74bbd:1 */
    /* note: Reached from first-stage island 0x33b4b6; the next linear thunk is 0xc57b8 but control leaves through computed jmp [rax]. */
    vm_note_second_stage_thunk(vm, edge, 0xc4258u, 0xc559du, "computed_indirect_target_unresolved", "instrument_or_symbolically_collapse_jmp_rax_memory_target");
}

static void second_stage_thunk_c57b8(VMState *vm, const VMNativeSecondStageThunk *edge) {
    /* entry=0xc57b8; scan=0xc57b8-0xc6bd0; setup_call_target=0xc57bd */
    /* loops: 0xc60ca->0xc60bb and 0xc69d2->0xc68b4; computed_jump=0xc6bce jmp [rax] */
    /* shape=call_plus_zero_stack_setup_two_internal_loops_computed_jmp_mem_rax; status=computed_indirect_target_unresolved; next_action=instrument_or_symbolically_collapse_jmp_rax_memory_target; next_linear_entry=0xc6d58 */
    /* first_stage_entries=0x36afd2; source_mix=entry_195:1; first_stage_windows=195@0x3655e4:0x779bd-0x77a3d:1 */
    /* note: Reached from first-stage island 0x36afd2; structurally matches the c4258/c6d58 computed-jump thunk family. */
    vm_note_second_stage_thunk(vm, edge, 0xc57b8u, 0xc6bceu, "computed_indirect_target_unresolved", "instrument_or_symbolically_collapse_jmp_rax_memory_target");
}

static void second_stage_thunk_c6d58(VMState *vm, const VMNativeSecondStageThunk *edge) {
    /* entry=0xc6d58; scan=0xc6d58-0xc80bb; setup_call_target=0xc6d5d */
    /* loops: 0xc764f->0xc7640 and 0xc7e9a->0xc7d7a; computed_jump=0xc80b9 jmp [rax] */
    /* shape=call_plus_zero_stack_setup_two_internal_loops_computed_jmp_mem_rax; status=computed_indirect_target_unresolved; next_action=instrument_or_symbolically_collapse_jmp_rax_memory_target; next_linear_entry=0xc823b */
    /* first_stage_entries=0x337d35; source_mix=entry_195:1; first_stage_windows=195@0x333bc9:0x748d8-0x74958:1 */
    /* note: Reached from first-stage island 0x337d35; exact indirect target at jmp [rax] remains the next native-control solve. */
    vm_note_second_stage_thunk(vm, edge, 0xc6d58u, 0xc80b9u, "computed_indirect_target_unresolved", "instrument_or_symbolically_collapse_jmp_rax_memory_target");
}

void vm_native_obfuscated_second_stage(VMState *vm, uint32_t entry,
                                       const VMNativeSecondStageThunk *edge) {
    switch (entry) {
    case 0xc9849u:
        second_stage_thunk_c9849(vm, edge);
        break;
    case 0xcaf2au:
        second_stage_thunk_caf2a(vm, edge);
        break;
    case 0xc4258u:
        second_stage_thunk_c4258(vm, edge);
        break;
    case 0xc57b8u:
        second_stage_thunk_c57b8(vm, edge);
        break;
    case 0xc6d58u:
        second_stage_thunk_c6d58(vm, edge);
        break;
    default:
        vm_note_second_stage_thunk(vm, edge, entry, 0, "unknown_second_stage_thunk", "needs_static_audit");
        break;
    }
}
