/*
 * Native ret-patch hidden-control bridge.
 *
 * Generated by vm_native_ret_patch_hidden_bridge_dump.c from the native
 * return-patch target atlas and the joined obfuscated-control model.
 */
#include <stdint.h>

typedef struct VMState {
    uint8_t *ip;
    uint32_t state;
    uint32_t flags;
    uint8_t byte;
} VMState;

typedef struct VMNativeRetPatchEvent {
    uint64_t vm_ip;
    uint32_t ret0;
    uint32_t ret1;
    uint16_t stack_off;
    uint32_t flags;
} VMNativeRetPatchEvent;

typedef struct VMNativeHiddenStack {
    const uint64_t *qwords;
    uint32_t qword_count;
} VMNativeHiddenStack;

extern uint64_t vm_native_obfuscated_control_model(VMState *vm, uint32_t island_entry,
                                                    const VMNativeHiddenStack *stack);

static void vm_note_native_ret_patch_hidden_bridge(VMState *vm, const VMNativeRetPatchEvent *event,
                                                   uint32_t hidden_entry, uint32_t downstream,
                                                   uint64_t target, const char *edge_kind,
                                                   const char *model, const char *status) {
    (void)vm;
    (void)event;
    (void)hidden_entry;
    (void)downstream;
    (void)target;
    (void)edge_kind;
    (void)model;
    (void)status;
}

static void vm_note_unknown_native_ret_patch_hidden_bridge(VMState *vm, const VMNativeRetPatchEvent *event) {
    (void)vm;
    (void)event;
}

static int ret_patch_hidden_195_daf39_call_23122(VMState *vm,
                                                   const VMNativeRetPatchEvent *event,
                                                   const VMNativeHiddenStack *stack) {
    /* ret-patch source=entry_195; vm_ip=0xdaf39; patched_ret=0x230d4; edge=call; edge_hits=1 */
    /* ret-patch evidence: kind=single_stack_return; seeds=frame_only_snapshot:1,full_gpr_snapshot:1; runs=vmtail-fakenet-w16:1,vmtail-live-residual-targets:1; relation=native_ret_patch_text_offset_not_vm_ip:2 */
    /* hidden entry=0x23122; kind=entry_helper; downstream=0xe0017; downstream_status=first_stage_obfuscated_island; model=entry_helper_to_source278_retdec_native_target */
    uint64_t target = vm_native_obfuscated_control_model(vm, 0x23122u, stack);
    if (target == 0) {
        target = 0xcdc60u;
    }
    vm_note_native_ret_patch_hidden_bridge(vm, event, 0x23122u, 0xe0017u, target,
                                           "call", "entry_helper_to_source278_retdec_native_target", "entry_helper_to_source278_retdec_target_joined");
    return 1;
}

static int ret_patch_hidden_195_daf39_jump_e0017(VMState *vm,
                                                   const VMNativeRetPatchEvent *event,
                                                   const VMNativeHiddenStack *stack) {
    /* ret-patch source=entry_195; vm_ip=0xdaf39; patched_ret=0x230d4; edge=jump; edge_hits=1 */
    /* ret-patch evidence: kind=single_stack_return; seeds=frame_only_snapshot:1,full_gpr_snapshot:1; runs=vmtail-fakenet-w16:1,vmtail-live-residual-targets:1; relation=native_ret_patch_text_offset_not_vm_ip:2 */
    /* hidden entry=0xe0017; kind=stack_obfuscated_island; downstream=0xcdc60; downstream_status=source278_retdec_covered; model=source278_retdec_native_target */
    uint64_t target = vm_native_obfuscated_control_model(vm, 0xe0017u, stack);
    if (target == 0) {
        target = 0xcdc60u;
    }
    vm_note_native_ret_patch_hidden_bridge(vm, event, 0xe0017u, 0xcdc60u, target,
                                           "jump", "source278_retdec_native_target", "source278_retdec_target_joined");
    return 1;
}

static int ret_patch_hidden_195_2304b8_jump_231586(VMState *vm,
                                                   const VMNativeRetPatchEvent *event,
                                                   const VMNativeHiddenStack *stack) {
    /* ret-patch source=entry_195; vm_ip=0x2304b8; patched_ret=0x44d7b; edge=jump; edge_hits=1 */
    /* ret-patch evidence: kind=single_stack_return; seeds=frame_only_snapshot:1,full_gpr_snapshot:1; runs=vmtail-fakenet-w16:1,vmtail-live-residual-targets:1; relation=native_ret_patch_text_offset_not_vm_ip:2 */
    /* hidden entry=0x231586; kind=stack_obfuscated_island; downstream=0xcf3c7; downstream_status=source278_retdec_covered; model=source278_retdec_native_target */
    uint64_t target = vm_native_obfuscated_control_model(vm, 0x231586u, stack);
    if (target == 0) {
        target = 0xcf3c7u;
    }
    vm_note_native_ret_patch_hidden_bridge(vm, event, 0x231586u, 0xcf3c7u, target,
                                           "jump", "source278_retdec_native_target", "source278_retdec_target_joined");
    return 1;
}

static int ret_patch_hidden_195_333bc9_jump_337d35(VMState *vm,
                                                   const VMNativeRetPatchEvent *event,
                                                   const VMNativeHiddenStack *stack) {
    /* ret-patch source=entry_195; vm_ip=0x333bc9; patched_ret=0x748d8; edge=jump; edge_hits=1 */
    /* ret-patch evidence: kind=single_stack_return; seeds=frame_only_snapshot:1,full_gpr_snapshot:1; runs=vmtail-fakenet-w16:1,vmtail-live-residual-targets:1; relation=native_ret_patch_text_offset_not_vm_ip:2 */
    /* hidden entry=0x337d35; kind=stack_obfuscated_island; downstream=0xc6d58; downstream_status=second_stage_obfuscated_thunk; model=dispatch_table[stack_qword(rsp+0x88)] */
    /* second_stage_entry=0xc6d58; indirect_jmp_site=0xc80b9; stack_source=static_stack_source_to_rbx_shift_proven; target_entry_mix=86@0x8a37f:1,310@0xb8556:3,169@0x9af18:4 */
    uint64_t target = vm_native_obfuscated_control_model(vm, 0x337d35u, stack);
    vm_note_native_ret_patch_hidden_bridge(vm, event, 0x337d35u, 0xc6d58u, target,
                                           "jump", "dispatch_table[stack_qword(rsp+0x88)]", "end_to_end_second_stage_dispatch_model_joined");
    return 1;
}

static int ret_patch_hidden_195_33d2d9_jump_33f109(VMState *vm,
                                                   const VMNativeRetPatchEvent *event,
                                                   const VMNativeHiddenStack *stack) {
    /* ret-patch source=entry_195; vm_ip=0x33d2d9; patched_ret=0x74f88; edge=jump; edge_hits=1 */
    /* ret-patch evidence: kind=single_stack_return; seeds=frame_only_snapshot:1,full_gpr_snapshot:1; runs=vmtail-fakenet-w16:1,vmtail-live-residual-targets:1; relation=native_ret_patch_text_offset_not_vm_ip:2 */
    /* hidden entry=0x33f109; kind=stack_obfuscated_island; downstream=0xcaf2a; downstream_status=second_stage_obfuscated_thunk; model=dispatch_table[stack_qword(rsp+0x88)] */
    /* second_stage_entry=0xcaf2a; indirect_jmp_site=0xcc3f5; stack_source=static_stack_source_to_rbx_shift_proven; target_entry_mix=86@0x8a37f:1,310@0xb8556:1,169@0x9af18:2 */
    uint64_t target = vm_native_obfuscated_control_model(vm, 0x33f109u, stack);
    vm_note_native_ret_patch_hidden_bridge(vm, event, 0x33f109u, 0xcaf2au, target,
                                           "jump", "dispatch_table[stack_qword(rsp+0x88)]", "end_to_end_second_stage_dispatch_model_joined");
    return 1;
}

static int ret_patch_hidden_195_3655e4_jump_36afd2(VMState *vm,
                                                   const VMNativeRetPatchEvent *event,
                                                   const VMNativeHiddenStack *stack) {
    /* ret-patch source=entry_195; vm_ip=0x3655e4; patched_ret=0x779bd; edge=jump; edge_hits=1 */
    /* ret-patch evidence: kind=single_stack_return; seeds=full_gpr_snapshot:2; runs=vmtail-live-residual-targets:1,vmtail-state-residual-targets:1; relation=native_ret_patch_text_offset_not_vm_ip:2 */
    /* hidden entry=0x36afd2; kind=stack_obfuscated_island; downstream=0xc57b8; downstream_status=second_stage_obfuscated_thunk; model=dispatch_table[stack_qword(rsp+0x88)] */
    /* second_stage_entry=0xc57b8; indirect_jmp_site=0xc6bce; stack_source=static_stack_source_to_rbx_shift_proven; target_entry_mix=86@0x8a37f:1,169@0x9af18:2,310@0xb8556:1 */
    uint64_t target = vm_native_obfuscated_control_model(vm, 0x36afd2u, stack);
    vm_note_native_ret_patch_hidden_bridge(vm, event, 0x36afd2u, 0xc57b8u, target,
                                           "jump", "dispatch_table[stack_qword(rsp+0x88)]", "end_to_end_second_stage_dispatch_model_joined");
    return 1;
}

static int ret_patch_hidden_299_17452e_jump_17bf1f(VMState *vm,
                                                   const VMNativeRetPatchEvent *event,
                                                   const VMNativeHiddenStack *stack) {
    /* ret-patch source=entry_299; vm_ip=0x17452e; patched_ret=0x313eb; edge=jump; edge_hits=1 */
    /* ret-patch evidence: kind=single_stack_return; seeds=full_gpr_snapshot:2; runs=vmtail-live-residual-targets:1,vmtail-state-residual-targets:1; relation=native_ret_patch_text_offset_not_vm_ip:2 */
    /* hidden entry=0x17bf1f; kind=stack_obfuscated_island; downstream=0xc9849; downstream_status=second_stage_obfuscated_thunk; model=dispatch_table[stack_qword(rsp+0x88)] */
    /* second_stage_entry=0xc9849; indirect_jmp_site=0xcad88; stack_source=static_stack_source_to_rbx_shift_proven; target_entry_mix=323@0xbb6e6:1,169@0x9af18:1,310@0xb8556:2 */
    uint64_t target = vm_native_obfuscated_control_model(vm, 0x17bf1fu, stack);
    vm_note_native_ret_patch_hidden_bridge(vm, event, 0x17bf1fu, 0xc9849u, target,
                                           "jump", "dispatch_table[stack_qword(rsp+0x88)]", "end_to_end_second_stage_dispatch_model_joined");
    return 1;
}

static int ret_patch_hidden_299_33710f_jump_33b4b6(VMState *vm,
                                                   const VMNativeRetPatchEvent *event,
                                                   const VMNativeHiddenStack *stack) {
    /* ret-patch source=entry_299; vm_ip=0x33710f; patched_ret=0x74b3d; edge=jump; edge_hits=1 */
    /* ret-patch evidence: kind=single_stack_return; seeds=frame_only_snapshot:1,full_gpr_snapshot:1; runs=vmtail-fakenet-w16:1,vmtail-live-residual-targets:1; relation=native_ret_patch_text_offset_not_vm_ip:2 */
    /* hidden entry=0x33b4b6; kind=stack_obfuscated_island; downstream=0xc4258; downstream_status=second_stage_obfuscated_thunk; model=dispatch_table[stack_qword(rsp+0x88)] */
    /* second_stage_entry=0xc4258; indirect_jmp_site=0xc559d; stack_source=static_stack_source_to_rbx_shift_proven; target_entry_mix=323@0xbb6e6:1,169@0x9af18:6,310@0xb8556:1 */
    uint64_t target = vm_native_obfuscated_control_model(vm, 0x33b4b6u, stack);
    vm_note_native_ret_patch_hidden_bridge(vm, event, 0x33b4b6u, 0xc4258u, target,
                                           "jump", "dispatch_table[stack_qword(rsp+0x88)]", "end_to_end_second_stage_dispatch_model_joined");
    return 1;
}

int vm_native_ret_patch_hidden_bridge_dispatch(VMState *vm, uint64_t vm_ip,
                                               uint32_t ret0, uint32_t ret1,
                                               uint16_t stack_off, uint32_t flags,
                                               const VMNativeHiddenStack *stack) {
    VMNativeRetPatchEvent event = { vm_ip, ret0, ret1, stack_off, flags };
    int hits = 0;
    (void)ret1;
    switch (vm_ip) {
    case 0xdaf39ull:
        if (ret0 == 0x230d4u) {
            hits += ret_patch_hidden_195_daf39_call_23122(vm, &event, stack);
            hits += ret_patch_hidden_195_daf39_jump_e0017(vm, &event, stack);
            return hits;
        }
        break;
    case 0x2304b8ull:
        if (ret0 == 0x44d7bu) {
            hits += ret_patch_hidden_195_2304b8_jump_231586(vm, &event, stack);
            return hits;
        }
        break;
    case 0x333bc9ull:
        if (ret0 == 0x748d8u) {
            hits += ret_patch_hidden_195_333bc9_jump_337d35(vm, &event, stack);
            return hits;
        }
        break;
    case 0x33d2d9ull:
        if (ret0 == 0x74f88u) {
            hits += ret_patch_hidden_195_33d2d9_jump_33f109(vm, &event, stack);
            return hits;
        }
        break;
    case 0x3655e4ull:
        if (ret0 == 0x779bdu) {
            hits += ret_patch_hidden_195_3655e4_jump_36afd2(vm, &event, stack);
            return hits;
        }
        break;
    case 0x17452eull:
        if (ret0 == 0x313ebu) {
            hits += ret_patch_hidden_299_17452e_jump_17bf1f(vm, &event, stack);
            return hits;
        }
        break;
    case 0x33710full:
        if (ret0 == 0x74b3du) {
            hits += ret_patch_hidden_299_33710f_jump_33b4b6(vm, &event, stack);
            return hits;
        }
        break;
    default:
        break;
    }
    vm_note_unknown_native_ret_patch_hidden_bridge(vm, &event);
    return hits;
}

void vm_native_ret_patch_hidden_bridge(VMState *vm, uint64_t vm_ip,
                                       uint32_t ret0, uint32_t ret1,
                                       uint16_t stack_off, uint32_t flags) {
    (void)vm_native_ret_patch_hidden_bridge_dispatch(vm, vm_ip, ret0, ret1,
                                                     stack_off, flags, 0);
}
