/*
 * Native obfuscated second-stage C model.
 *
 * Generated by vm_native_obfuscated_second_stage_model_dump.c from
 * static thunk structure, dynamic dispatch evidence, slot formula proof,
 * and RBX provenance probe artifacts.
 */
#include <stdint.h>

typedef struct VMState {
    uint64_t dispatch_table_base;
    const uint64_t *dispatch_table;
    uint32_t dispatch_table_entries;
} VMState;

typedef struct VMSecondStageNativeStack {
    const uint64_t *qwords;
    uint32_t qword_count;
} VMSecondStageNativeStack;

static uint64_t vm_second_stage_stack_qword(const VMSecondStageNativeStack *stack, uint32_t byte_off) {
    uint32_t index = byte_off >> 3;
    if (!stack || !stack->qwords || index >= stack->qword_count) {
        return 0;
    }
    return stack->qwords[index];
}

static uint64_t vm_second_stage_dispatch_target(const VMState *vm, uint64_t handler_entry) {
    uint64_t slot = (vm ? vm->dispatch_table_base : 0) + (handler_entry << 3);
    if (vm && vm->dispatch_table && handler_entry < vm->dispatch_table_entries) {
        return vm->dispatch_table[handler_entry];
    }
    return slot;
}

static void vm_note_second_stage_model(VMState *vm, const VMSecondStageNativeStack *stack,
                                       uint32_t entry, uint32_t site,
                                       uint64_t handler_entry, uint64_t observed_vm_ip,
                                       uint64_t dispatch_index, uint64_t target,
                                       const char *target_entry_mix,
                                       const char *status) {
    (void)vm;
    (void)stack;
    (void)entry;
    (void)site;
    (void)handler_entry;
    (void)observed_vm_ip;
    (void)dispatch_index;
    (void)target;
    (void)target_entry_mix;
    (void)status;
}

static void second_stage_model_cad88(VMState *vm, const VMSecondStageNativeStack *stack) {
    uint64_t handler_entry = vm_second_stage_stack_qword(stack, 0x88u);
    uint64_t observed_vm_ip = vm_second_stage_stack_qword(stack, 0x90u);
    uint64_t dispatch_index = handler_entry << 3;
    uint64_t target = vm_second_stage_dispatch_target(vm, handler_entry);
    /* entry=0xc9849; site=0xcad88; first_stage=0x17bf1f; chain=source299_chain_a */
    /* formula=rax_final=rax_initial+(rbx<<3); stack_source=push=0xcaca3,load=0xcacb0,shift=0xcacf1; stack_source_status=static_stack_source_to_rbx_shift_proven; handler_entry_mix=0x143:1,0xa9:1; target_entry_mix=323@0xbb6e6:1,169@0x9af18:1,310@0xb8556:2 */
    /* slot_base_check=slot_minus_idx_matches_dispatch_table:4; slot_target_check=slot_index_matches_handler_target:4; model_status=static_stack_handler_entry_dispatch_model_for_observed_hits */
    vm_note_second_stage_model(vm, stack, 0xc9849u, 0xcad88u, handler_entry,
                               observed_vm_ip, dispatch_index, target, "323@0xbb6e6:1,169@0x9af18:1,310@0xb8556:2", "static_stack_handler_entry_dispatch_model_for_observed_hits");
}

static void second_stage_model_cc3f5(VMState *vm, const VMSecondStageNativeStack *stack) {
    uint64_t handler_entry = vm_second_stage_stack_qword(stack, 0x88u);
    uint64_t observed_vm_ip = vm_second_stage_stack_qword(stack, 0x90u);
    uint64_t dispatch_index = handler_entry << 3;
    uint64_t target = vm_second_stage_dispatch_target(vm, handler_entry);
    /* entry=0xcaf2a; site=0xcc3f5; first_stage=0x33f109; chain=source195_chain_b */
    /* formula=rax_final=rax_initial+(rbx<<3); stack_source=push=0xcc31c,load=0xcc326,shift=0xcc36a; stack_source_status=static_stack_source_to_rbx_shift_proven; handler_entry_mix=0x56:1,0x136:1; target_entry_mix=86@0x8a37f:1,310@0xb8556:1,169@0x9af18:2 */
    /* slot_base_check=slot_minus_idx_matches_dispatch_table:4; slot_target_check=slot_index_matches_handler_target:4; model_status=static_stack_handler_entry_dispatch_model_for_observed_hits */
    vm_note_second_stage_model(vm, stack, 0xcaf2au, 0xcc3f5u, handler_entry,
                               observed_vm_ip, dispatch_index, target, "86@0x8a37f:1,310@0xb8556:1,169@0x9af18:2", "static_stack_handler_entry_dispatch_model_for_observed_hits");
}

static void second_stage_model_c559d(VMState *vm, const VMSecondStageNativeStack *stack) {
    uint64_t handler_entry = vm_second_stage_stack_qword(stack, 0x88u);
    uint64_t observed_vm_ip = vm_second_stage_stack_qword(stack, 0x90u);
    uint64_t dispatch_index = handler_entry << 3;
    uint64_t target = vm_second_stage_dispatch_target(vm, handler_entry);
    /* entry=0xc4258; site=0xc559d; first_stage=0x33b4b6; chain=source299_chain_b */
    /* formula=rax_final=rax_initial+(rbx<<3); stack_source=push=0xc54c6,load=0xc54d3,shift=0xc5512; stack_source_status=static_stack_source_to_rbx_shift_proven; handler_entry_mix=0x143:1,0xa9:1; target_entry_mix=323@0xbb6e6:1,169@0x9af18:6,310@0xb8556:1 */
    /* slot_base_check=slot_minus_idx_matches_dispatch_table:8; slot_target_check=slot_index_matches_handler_target:8; model_status=static_stack_handler_entry_dispatch_model_for_observed_hits */
    vm_note_second_stage_model(vm, stack, 0xc4258u, 0xc559du, handler_entry,
                               observed_vm_ip, dispatch_index, target, "323@0xbb6e6:1,169@0x9af18:6,310@0xb8556:1", "static_stack_handler_entry_dispatch_model_for_observed_hits");
}

static void second_stage_model_c6bce(VMState *vm, const VMSecondStageNativeStack *stack) {
    uint64_t handler_entry = vm_second_stage_stack_qword(stack, 0x88u);
    uint64_t observed_vm_ip = vm_second_stage_stack_qword(stack, 0x90u);
    uint64_t dispatch_index = handler_entry << 3;
    uint64_t target = vm_second_stage_dispatch_target(vm, handler_entry);
    /* entry=0xc57b8; site=0xc6bce; first_stage=0x36afd2; chain=source195_chain_c */
    /* formula=rax_final=rax_initial+(rbx<<3); stack_source=push=0xc6afc,load=0xc6b09,shift=0xc6b43; stack_source_status=static_stack_source_to_rbx_shift_proven; handler_entry_mix=0x56:1,0xa9:1; target_entry_mix=86@0x8a37f:1,169@0x9af18:2,310@0xb8556:1 */
    /* slot_base_check=slot_minus_idx_matches_dispatch_table:4; slot_target_check=slot_index_matches_handler_target:4; model_status=static_stack_handler_entry_dispatch_model_for_observed_hits */
    vm_note_second_stage_model(vm, stack, 0xc57b8u, 0xc6bceu, handler_entry,
                               observed_vm_ip, dispatch_index, target, "86@0x8a37f:1,169@0x9af18:2,310@0xb8556:1", "static_stack_handler_entry_dispatch_model_for_observed_hits");
}

static void second_stage_model_c80b9(VMState *vm, const VMSecondStageNativeStack *stack) {
    uint64_t handler_entry = vm_second_stage_stack_qword(stack, 0x88u);
    uint64_t observed_vm_ip = vm_second_stage_stack_qword(stack, 0x90u);
    uint64_t dispatch_index = handler_entry << 3;
    uint64_t target = vm_second_stage_dispatch_target(vm, handler_entry);
    /* entry=0xc6d58; site=0xc80b9; first_stage=0x337d35; chain=source195_chain_d */
    /* formula=rax_final=rax_initial+(rbx<<3); stack_source=push=0xc7fdc,load=0xc7fe6,shift=0xc802e; stack_source_status=static_stack_source_to_rbx_shift_proven; handler_entry_mix=0x56:1,0x136:1; target_entry_mix=86@0x8a37f:1,310@0xb8556:3,169@0x9af18:4 */
    /* slot_base_check=slot_minus_idx_matches_dispatch_table:8; slot_target_check=slot_index_matches_handler_target:8; model_status=static_stack_handler_entry_dispatch_model_for_observed_hits */
    vm_note_second_stage_model(vm, stack, 0xc6d58u, 0xc80b9u, handler_entry,
                               observed_vm_ip, dispatch_index, target, "86@0x8a37f:1,310@0xb8556:3,169@0x9af18:4", "static_stack_handler_entry_dispatch_model_for_observed_hits");
}

void vm_native_obfuscated_second_stage_model(VMState *vm, uint32_t indirect_jmp_site,
                                             const VMSecondStageNativeStack *stack) {
    switch (indirect_jmp_site) {
    case 0xcad88u:
        second_stage_model_cad88(vm, stack);
        break;
    case 0xcc3f5u:
        second_stage_model_cc3f5(vm, stack);
        break;
    case 0xc559du:
        second_stage_model_c559d(vm, stack);
        break;
    case 0xc6bceu:
        second_stage_model_c6bce(vm, stack);
        break;
    case 0xc80b9u:
        second_stage_model_c80b9(vm, stack);
        break;
    default:
        vm_note_second_stage_model(vm, stack, 0, indirect_jmp_site, 0, 0, 0, 0,
                                   "-", "unknown_second_stage_model_site");
        break;
    }
}
