/*
 * Native obfuscated hidden-control model.
 *
 * Generated by vm_native_obfuscated_control_model_dump.c from
 * ret-patch follow-up island rows and the second-stage dispatch model.
 */
#include <stdint.h>

typedef struct VMState {
    uint64_t dispatch_table_base;
    const uint64_t *dispatch_table;
    uint32_t dispatch_table_entries;
} VMState;

typedef struct VMNativeHiddenStack {
    const uint64_t *qwords;
    uint32_t qword_count;
} VMNativeHiddenStack;

static uint64_t vm_native_hidden_stack_qword(const VMNativeHiddenStack *stack, uint32_t byte_off) {
    uint32_t index = byte_off >> 3;
    if (!stack || !stack->qwords || index >= stack->qword_count) {
        return 0;
    }
    return stack->qwords[index];
}

static uint64_t vm_native_hidden_dispatch_target(const VMState *vm, uint64_t handler_entry) {
    uint64_t slot = (vm ? vm->dispatch_table_base : 0) + (handler_entry << 3);
    if (vm && vm->dispatch_table && handler_entry < vm->dispatch_table_entries) {
        return vm->dispatch_table[handler_entry];
    }
    return slot;
}

static void vm_note_native_obfuscated_control(VMState *vm, const VMNativeHiddenStack *stack,
                                             uint32_t island_entry, uint32_t downstream,
                                             uint64_t target, uint64_t handler_entry,
                                             uint64_t observed_vm_ip, uint64_t dispatch_index,
                                             const char *status) {
    (void)vm;
    (void)stack;
    (void)island_entry;
    (void)downstream;
    (void)target;
    (void)handler_entry;
    (void)observed_vm_ip;
    (void)dispatch_index;
    (void)status;
}

static uint64_t native_obfuscated_control_23122(VMState *vm, const VMNativeHiddenStack *stack) {
    /* source_mix=entry_195:1; window_mix=195@0xdaf39:0x230d4-0x23154:1 */
    /* entry=0x23122; kind=entry_helper; downstream=0xe0017; downstream_status=first_stage_obfuscated_island; final_model=entry_helper_to_source278_retdec_native_target */
    uint64_t target = 0xcdc60u;
    vm_note_native_obfuscated_control(vm, stack, 0x23122u, 0xe0017u, target,
                                      0, 0, 0, "entry_helper_to_source278_retdec_target_joined");
    return target;
}

static uint64_t native_obfuscated_control_e0017(VMState *vm, const VMNativeHiddenStack *stack) {
    /* source_mix=entry_195:1; window_mix=195@0xdaf39:0x230d4-0x23154:1 */
    /* entry=0xe0017; kind=stack_obfuscated_island; downstream=0xcdc60; downstream_status=source278_retdec_covered; final_model=source278_retdec_native_target */
    uint64_t target = 0xcdc60u;
    vm_note_native_obfuscated_control(vm, stack, 0xe0017u, 0xcdc60u, target,
                                      0, 0, 0, "source278_retdec_target_joined");
    return target;
}

static uint64_t native_obfuscated_control_17bf1f(VMState *vm, const VMNativeHiddenStack *stack) {
    /* source_mix=entry_299:1; window_mix=299@0x17452e:0x313eb-0x3146b:1 */
    /* entry=0x17bf1f; kind=stack_obfuscated_island; downstream=0xc9849; downstream_status=second_stage_obfuscated_thunk; final_model=dispatch_table[stack_qword(rsp+0x88)] */
    uint64_t handler_entry = vm_native_hidden_stack_qword(stack, 0x88u);
    uint64_t observed_vm_ip = vm_native_hidden_stack_qword(stack, 0x90u);
    uint64_t dispatch_index = handler_entry << 3;
    uint64_t target = vm_native_hidden_dispatch_target(vm, handler_entry);
    /* second_stage_entry=0xc9849; indirect_jmp_site=0xcad88; stack_source=push=0xcaca3,load=0xcacb0,shift=0xcacf1; model_status=static_stack_handler_entry_dispatch_model_for_observed_hits */
    /* handler_entry_mix=0x143:1,0xa9:1; target_entry_mix=323@0xbb6e6:1,169@0x9af18:1,310@0xb8556:2 */
    vm_note_native_obfuscated_control(vm, stack, 0x17bf1fu, 0xc9849u, target,
                                      handler_entry, observed_vm_ip, dispatch_index, "end_to_end_second_stage_dispatch_model_joined");
    return target;
}

static uint64_t native_obfuscated_control_231586(VMState *vm, const VMNativeHiddenStack *stack) {
    /* source_mix=entry_195:1; window_mix=195@0x2304b8:0x44d7b-0x44dfb:1 */
    /* entry=0x231586; kind=stack_obfuscated_island; downstream=0xcf3c7; downstream_status=source278_retdec_covered; final_model=source278_retdec_native_target */
    uint64_t target = 0xcf3c7u;
    vm_note_native_obfuscated_control(vm, stack, 0x231586u, 0xcf3c7u, target,
                                      0, 0, 0, "source278_retdec_target_joined");
    return target;
}

static uint64_t native_obfuscated_control_337d35(VMState *vm, const VMNativeHiddenStack *stack) {
    /* source_mix=entry_195:1; window_mix=195@0x333bc9:0x748d8-0x74958:1 */
    /* entry=0x337d35; kind=stack_obfuscated_island; downstream=0xc6d58; downstream_status=second_stage_obfuscated_thunk; final_model=dispatch_table[stack_qword(rsp+0x88)] */
    uint64_t handler_entry = vm_native_hidden_stack_qword(stack, 0x88u);
    uint64_t observed_vm_ip = vm_native_hidden_stack_qword(stack, 0x90u);
    uint64_t dispatch_index = handler_entry << 3;
    uint64_t target = vm_native_hidden_dispatch_target(vm, handler_entry);
    /* second_stage_entry=0xc6d58; indirect_jmp_site=0xc80b9; stack_source=push=0xc7fdc,load=0xc7fe6,shift=0xc802e; model_status=static_stack_handler_entry_dispatch_model_for_observed_hits */
    /* handler_entry_mix=0x56:1,0x136:1; target_entry_mix=86@0x8a37f:1,310@0xb8556:3,169@0x9af18:4 */
    vm_note_native_obfuscated_control(vm, stack, 0x337d35u, 0xc6d58u, target,
                                      handler_entry, observed_vm_ip, dispatch_index, "end_to_end_second_stage_dispatch_model_joined");
    return target;
}

static uint64_t native_obfuscated_control_33b4b6(VMState *vm, const VMNativeHiddenStack *stack) {
    /* source_mix=entry_299:1; window_mix=299@0x33710f:0x74b3d-0x74bbd:1 */
    /* entry=0x33b4b6; kind=stack_obfuscated_island; downstream=0xc4258; downstream_status=second_stage_obfuscated_thunk; final_model=dispatch_table[stack_qword(rsp+0x88)] */
    uint64_t handler_entry = vm_native_hidden_stack_qword(stack, 0x88u);
    uint64_t observed_vm_ip = vm_native_hidden_stack_qword(stack, 0x90u);
    uint64_t dispatch_index = handler_entry << 3;
    uint64_t target = vm_native_hidden_dispatch_target(vm, handler_entry);
    /* second_stage_entry=0xc4258; indirect_jmp_site=0xc559d; stack_source=push=0xc54c6,load=0xc54d3,shift=0xc5512; model_status=static_stack_handler_entry_dispatch_model_for_observed_hits */
    /* handler_entry_mix=0x143:1,0xa9:1; target_entry_mix=323@0xbb6e6:1,169@0x9af18:6,310@0xb8556:1 */
    vm_note_native_obfuscated_control(vm, stack, 0x33b4b6u, 0xc4258u, target,
                                      handler_entry, observed_vm_ip, dispatch_index, "end_to_end_second_stage_dispatch_model_joined");
    return target;
}

static uint64_t native_obfuscated_control_33f109(VMState *vm, const VMNativeHiddenStack *stack) {
    /* source_mix=entry_195:1; window_mix=195@0x33d2d9:0x74f88-0x75008:1 */
    /* entry=0x33f109; kind=stack_obfuscated_island; downstream=0xcaf2a; downstream_status=second_stage_obfuscated_thunk; final_model=dispatch_table[stack_qword(rsp+0x88)] */
    uint64_t handler_entry = vm_native_hidden_stack_qword(stack, 0x88u);
    uint64_t observed_vm_ip = vm_native_hidden_stack_qword(stack, 0x90u);
    uint64_t dispatch_index = handler_entry << 3;
    uint64_t target = vm_native_hidden_dispatch_target(vm, handler_entry);
    /* second_stage_entry=0xcaf2a; indirect_jmp_site=0xcc3f5; stack_source=push=0xcc31c,load=0xcc326,shift=0xcc36a; model_status=static_stack_handler_entry_dispatch_model_for_observed_hits */
    /* handler_entry_mix=0x56:1,0x136:1; target_entry_mix=86@0x8a37f:1,310@0xb8556:1,169@0x9af18:2 */
    vm_note_native_obfuscated_control(vm, stack, 0x33f109u, 0xcaf2au, target,
                                      handler_entry, observed_vm_ip, dispatch_index, "end_to_end_second_stage_dispatch_model_joined");
    return target;
}

static uint64_t native_obfuscated_control_36afd2(VMState *vm, const VMNativeHiddenStack *stack) {
    /* source_mix=entry_195:1; window_mix=195@0x3655e4:0x779bd-0x77a3d:1 */
    /* entry=0x36afd2; kind=stack_obfuscated_island; downstream=0xc57b8; downstream_status=second_stage_obfuscated_thunk; final_model=dispatch_table[stack_qword(rsp+0x88)] */
    uint64_t handler_entry = vm_native_hidden_stack_qword(stack, 0x88u);
    uint64_t observed_vm_ip = vm_native_hidden_stack_qword(stack, 0x90u);
    uint64_t dispatch_index = handler_entry << 3;
    uint64_t target = vm_native_hidden_dispatch_target(vm, handler_entry);
    /* second_stage_entry=0xc57b8; indirect_jmp_site=0xc6bce; stack_source=push=0xc6afc,load=0xc6b09,shift=0xc6b43; model_status=static_stack_handler_entry_dispatch_model_for_observed_hits */
    /* handler_entry_mix=0x56:1,0xa9:1; target_entry_mix=86@0x8a37f:1,169@0x9af18:2,310@0xb8556:1 */
    vm_note_native_obfuscated_control(vm, stack, 0x36afd2u, 0xc57b8u, target,
                                      handler_entry, observed_vm_ip, dispatch_index, "end_to_end_second_stage_dispatch_model_joined");
    return target;
}

uint64_t vm_native_obfuscated_control_model(VMState *vm, uint32_t island_entry,
                                            const VMNativeHiddenStack *stack) {
    switch (island_entry) {
    case 0x23122u:
        return native_obfuscated_control_23122(vm, stack);
    case 0xe0017u:
        return native_obfuscated_control_e0017(vm, stack);
    case 0x17bf1fu:
        return native_obfuscated_control_17bf1f(vm, stack);
    case 0x231586u:
        return native_obfuscated_control_231586(vm, stack);
    case 0x337d35u:
        return native_obfuscated_control_337d35(vm, stack);
    case 0x33b4b6u:
        return native_obfuscated_control_33b4b6(vm, stack);
    case 0x33f109u:
        return native_obfuscated_control_33f109(vm, stack);
    case 0x36afd2u:
        return native_obfuscated_control_36afd2(vm, stack);
    default:
        vm_note_native_obfuscated_control(vm, stack, island_entry, 0, 0, 0, 0, 0,
                                         "unknown_native_obfuscated_control_entry");
        return 0;
    }
}
