/*
 * Native obfuscated second-stage RBX provenance evidence.
 *
 * Generated by vm_native_obfuscated_second_stage_rbx_provenance_dump.c
 * from generic single-step probe logs. It proves, for observed hits, that
 * push 0x88(%rsp) carries the handler entry, the rbx load receives that
 * value, and the later dispatch idx is rbx << 3.
 */
#include <stdint.h>

typedef struct VMState {
    uint8_t *ip;
    uint32_t state;
    uint32_t flags;
    uint8_t byte;
} VMState;

typedef struct VMSecondStageRBXProvenance {
    uint32_t entry;
    uint32_t indirect_jmp_site;
    const char *handler_entry_mix;
} VMSecondStageRBXProvenance;

static void vm_note_second_stage_rbx_provenance(VMState *vm,
                                                    const VMSecondStageRBXProvenance *edge,
                                                    uint32_t entry, uint32_t site,
                                                    unsigned observed_rows,
                                                    const char *handler_entry_mix,
                                                    const char *status) {
    (void)vm;
    (void)edge;
    (void)entry;
    (void)site;
    (void)observed_rows;
    (void)handler_entry_mix;
    (void)status;
}

static void second_stage_rbx_provenance_cad88(VMState *vm, const VMSecondStageRBXProvenance *edge) {
    /* entry=0xc9849; dispatch_site=0xcad88; push_site=0xcaca3; load_site=0xcacb0; shift_site=0xcacf1 */
    /* handler_entry_mix=0x143:1,0xa9:1; target_mix=0xbb6e6:1,0x9af18:1; complete=2; push_match=2; load_match=2; shift_match=2; vmip_match=2 */
    vm_note_second_stage_rbx_provenance(vm, edge, 0xc9849u, 0xcad88u, 2u, "0x143:1,0xa9:1", "rbx_stack_entry_to_dispatch_index_proven_for_observed_hits");
}

static void second_stage_rbx_provenance_cc3f5(VMState *vm, const VMSecondStageRBXProvenance *edge) {
    /* entry=0xcaf2a; dispatch_site=0xcc3f5; push_site=0xcc31c; load_site=0xcc326; shift_site=0xcc36a */
    /* handler_entry_mix=0x56:1,0x136:1; target_mix=0x8a37f:1,0xb8556:1; complete=2; push_match=2; load_match=2; shift_match=2; vmip_match=2 */
    vm_note_second_stage_rbx_provenance(vm, edge, 0xcaf2au, 0xcc3f5u, 2u, "0x56:1,0x136:1", "rbx_stack_entry_to_dispatch_index_proven_for_observed_hits");
}

static void second_stage_rbx_provenance_c559d(VMState *vm, const VMSecondStageRBXProvenance *edge) {
    /* entry=0xc4258; dispatch_site=0xc559d; push_site=0xc54c6; load_site=0xc54d3; shift_site=0xc5512 */
    /* handler_entry_mix=0x143:1,0xa9:1; target_mix=0xbb6e6:1,0x9af18:1; complete=2; push_match=2; load_match=2; shift_match=2; vmip_match=2 */
    vm_note_second_stage_rbx_provenance(vm, edge, 0xc4258u, 0xc559du, 2u, "0x143:1,0xa9:1", "rbx_stack_entry_to_dispatch_index_proven_for_observed_hits");
}

static void second_stage_rbx_provenance_c6bce(VMState *vm, const VMSecondStageRBXProvenance *edge) {
    /* entry=0xc57b8; dispatch_site=0xc6bce; push_site=0xc6afc; load_site=0xc6b09; shift_site=0xc6b43 */
    /* handler_entry_mix=0x56:1,0xa9:1; target_mix=0x8a37f:1,0x9af18:1; complete=2; push_match=2; load_match=2; shift_match=2; vmip_match=2 */
    vm_note_second_stage_rbx_provenance(vm, edge, 0xc57b8u, 0xc6bceu, 2u, "0x56:1,0xa9:1", "rbx_stack_entry_to_dispatch_index_proven_for_observed_hits");
}

static void second_stage_rbx_provenance_c80b9(VMState *vm, const VMSecondStageRBXProvenance *edge) {
    /* entry=0xc6d58; dispatch_site=0xc80b9; push_site=0xc7fdc; load_site=0xc7fe6; shift_site=0xc802e */
    /* handler_entry_mix=0x56:1,0x136:1; target_mix=0x8a37f:1,0xb8556:1; complete=2; push_match=2; load_match=2; shift_match=2; vmip_match=2 */
    vm_note_second_stage_rbx_provenance(vm, edge, 0xc6d58u, 0xc80b9u, 2u, "0x56:1,0x136:1", "rbx_stack_entry_to_dispatch_index_proven_for_observed_hits");
}

void vm_native_obfuscated_second_stage_rbx_provenance(VMState *vm,
                                                       uint32_t indirect_jmp_site,
                                                       const VMSecondStageRBXProvenance *edge) {
    switch (indirect_jmp_site) {
    case 0xcad88u:
        second_stage_rbx_provenance_cad88(vm, edge);
        break;
    case 0xcc3f5u:
        second_stage_rbx_provenance_cc3f5(vm, edge);
        break;
    case 0xc559du:
        second_stage_rbx_provenance_c559d(vm, edge);
        break;
    case 0xc6bceu:
        second_stage_rbx_provenance_c6bce(vm, edge);
        break;
    case 0xc80b9u:
        second_stage_rbx_provenance_c80b9(vm, edge);
        break;
    default:
        vm_note_second_stage_rbx_provenance(vm, edge, 0, indirect_jmp_site, 0,
                                             "-", "unknown_rbx_provenance_site");
        break;
    }
}
