/*
 * Native obfuscated island reconstruction map.
 *
 * Generated by vm_native_obfuscated_islands_dump.c from dumps/vmtail-wide-1m-w16/vm_native_ret_patch_followups.tsv plus
 * bounded objdump collapse facts for the first obfuscation stage.
 * This artifact is intentionally C-shaped: every return-patch island is
 * represented as an explicit helper and the dispatcher records whether the
 * collapsed downstream is already represented by targeted RetDec or still
 * needs a second-stage obfuscation collapse.
 */
#include <stdint.h>

typedef struct VMState {
    uint8_t *ip;
    uint32_t state;
    uint32_t flags;
    uint8_t byte;
} VMState;

typedef struct VMNativeObfuscatedIslandEvidence {
    uint64_t source_entry;
    uint64_t synthetic_start_vm_ip;
    uint32_t patched_ret_eac_off;
    const char *source_mix;
} VMNativeObfuscatedIslandEvidence;

static void vm_note_native_obfuscated_island(VMState *vm,
                                             const VMNativeObfuscatedIslandEvidence *edge,
                                             uint32_t entry, uint32_t downstream,
                                             const char *kind,
                                             const char *downstream_status) {
    (void)vm;
    (void)edge;
    (void)entry;
    (void)downstream;
    (void)kind;
    (void)downstream_status;
}

static void obfuscated_island_23122(VMState *vm, const VMNativeObfuscatedIslandEvidence *edge) {
    /* entry=0x23122; kind=entry_helper; range=0x23122-0x2314f */
    /* collapse_shape=normal_prologue_stack_cookie_then_direct_jump; final_jump_site=0x2314a; downstream=0xe0017 */
    /* downstream_status=first_stage_obfuscated_island; coverage=covered_by_obfuscated_island_map; next_action=follow_downstream_island */
    /* followup_classification=internal_obfuscated_helper_to_e0017; priority=targeted_obfuscation_candidate; sources=entry_195:1 */
    /* relation_mix=inside_retpatch_window:1; windows=195@0xdaf39:0x230d4-0x23154:1 */
    /* note: Helper has a conventional prologue, records a zero local, then jumps directly into the 0xe0017 native obfuscation island. */
    vm_note_native_obfuscated_island(vm, edge, 0x23122u, 0xe0017u, "entry_helper", "first_stage_obfuscated_island");
}

static void obfuscated_island_e0017(VMState *vm, const VMNativeObfuscatedIslandEvidence *edge) {
    /* entry=0xe0017; kind=stack_obfuscated_island; range=0xe0017-0xe0166 */
    /* collapse_shape=pushf_stack_register_permutation_then_direct_jump; final_jump_site=0xe0161; downstream=0xcdc60 */
    /* downstream_status=source278_retdec_covered; coverage=covered_by_vm_native_ret_patch_source278_retdec; next_action=join_existing_source278_retdec */
    /* followup_classification=obfuscated_native_island; priority=obfuscation_island_candidate; sources=entry_195:1 */
    /* relation_mix=outside_retpatch_window:1; windows=195@0xdaf39:0x230d4-0x23154:1 */
    /* note: Stack/flag permutation island collapses to 0xcdc60, already emitted in the source278 targeted RetDec sidecar. */
    vm_note_native_obfuscated_island(vm, edge, 0xe0017u, 0xcdc60u, "stack_obfuscated_island", "source278_retdec_covered");
}

static void obfuscated_island_17bf1f(VMState *vm, const VMNativeObfuscatedIslandEvidence *edge) {
    /* entry=0x17bf1f; kind=stack_obfuscated_island; range=0x17bf1f-0x17c085 */
    /* collapse_shape=pushf_stack_register_permutation_then_direct_jump; final_jump_site=0x17c080; downstream=0xc9849 */
    /* downstream_status=second_stage_obfuscated_thunk; coverage=needs_second_stage_obfuscation_collapse; next_action=decode_downstream_stack_thunk */
    /* followup_classification=obfuscated_native_island; priority=obfuscation_island_candidate; sources=entry_299:1 */
    /* relation_mix=outside_retpatch_window:1; windows=299@0x17452e:0x313eb-0x3146b:1 */
    /* note: Source 299 island collapses to 0xc9849, which begins as another stack/call obfuscation thunk rather than a normal C function. */
    vm_note_native_obfuscated_island(vm, edge, 0x17bf1fu, 0xc9849u, "stack_obfuscated_island", "second_stage_obfuscated_thunk");
}

static void obfuscated_island_231586(VMState *vm, const VMNativeObfuscatedIslandEvidence *edge) {
    /* entry=0x231586; kind=stack_obfuscated_island; range=0x231586-0x2316b6 */
    /* collapse_shape=pushf_stack_register_permutation_then_direct_jump; final_jump_site=0x2316b1; downstream=0xcf3c7 */
    /* downstream_status=source278_retdec_covered; coverage=covered_by_vm_native_ret_patch_source278_retdec; next_action=join_existing_source278_retdec */
    /* followup_classification=obfuscated_native_island; priority=obfuscation_island_candidate; sources=entry_195:1 */
    /* relation_mix=outside_retpatch_window:1; windows=195@0x2304b8:0x44d7b-0x44dfb:1 */
    /* note: Stack/flag permutation island collapses to 0xcf3c7, already emitted in the source278 targeted RetDec sidecar. */
    vm_note_native_obfuscated_island(vm, edge, 0x231586u, 0xcf3c7u, "stack_obfuscated_island", "source278_retdec_covered");
}

static void obfuscated_island_337d35(VMState *vm, const VMNativeObfuscatedIslandEvidence *edge) {
    /* entry=0x337d35; kind=stack_obfuscated_island; range=0x337d35-0x337e7b */
    /* collapse_shape=pushf_stack_register_permutation_then_direct_jump; final_jump_site=0x337e76; downstream=0xc6d58 */
    /* downstream_status=second_stage_obfuscated_thunk; coverage=needs_second_stage_obfuscation_collapse; next_action=decode_downstream_stack_thunk */
    /* followup_classification=obfuscated_native_island; priority=obfuscation_island_candidate; sources=entry_195:1 */
    /* relation_mix=outside_retpatch_window:1; windows=195@0x333bc9:0x748d8-0x74958:1 */
    /* note: Source 195 island collapses to 0xc6d58, which starts with a call/pop-style obfuscation thunk. */
    vm_note_native_obfuscated_island(vm, edge, 0x337d35u, 0xc6d58u, "stack_obfuscated_island", "second_stage_obfuscated_thunk");
}

static void obfuscated_island_33b4b6(VMState *vm, const VMNativeObfuscatedIslandEvidence *edge) {
    /* entry=0x33b4b6; kind=stack_obfuscated_island; range=0x33b4b6-0x33b642 */
    /* collapse_shape=pushf_stack_register_permutation_then_direct_jump; final_jump_site=0x33b63d; downstream=0xc4258 */
    /* downstream_status=second_stage_obfuscated_thunk; coverage=needs_second_stage_obfuscation_collapse; next_action=decode_downstream_stack_thunk */
    /* followup_classification=obfuscated_native_island; priority=obfuscation_island_candidate; sources=entry_299:1 */
    /* relation_mix=outside_retpatch_window:1; windows=299@0x33710f:0x74b3d-0x74bbd:1 */
    /* note: Source 299 island collapses to 0xc4258, whose downstream bytes are still obfuscated stack code. */
    vm_note_native_obfuscated_island(vm, edge, 0x33b4b6u, 0xc4258u, "stack_obfuscated_island", "second_stage_obfuscated_thunk");
}

static void obfuscated_island_33f109(VMState *vm, const VMNativeObfuscatedIslandEvidence *edge) {
    /* entry=0x33f109; kind=stack_obfuscated_island; range=0x33f109-0x33f273 */
    /* collapse_shape=pushf_stack_register_permutation_then_direct_jump; final_jump_site=0x33f26e; downstream=0xcaf2a */
    /* downstream_status=second_stage_obfuscated_thunk; coverage=needs_second_stage_obfuscation_collapse; next_action=decode_downstream_stack_thunk */
    /* followup_classification=obfuscated_native_island; priority=obfuscation_island_candidate; sources=entry_195:1 */
    /* relation_mix=outside_retpatch_window:1; windows=195@0x33d2d9:0x74f88-0x75008:1 */
    /* note: Source 195 island collapses to 0xcaf2a, which begins with a call into more stack/register obfuscation. */
    vm_note_native_obfuscated_island(vm, edge, 0x33f109u, 0xcaf2au, "stack_obfuscated_island", "second_stage_obfuscated_thunk");
}

static void obfuscated_island_36afd2(VMState *vm, const VMNativeObfuscatedIslandEvidence *edge) {
    /* entry=0x36afd2; kind=stack_obfuscated_island; range=0x36afd2-0x36b11b */
    /* collapse_shape=pushf_stack_register_permutation_then_direct_jump; final_jump_site=0x36b116; downstream=0xc57b8 */
    /* downstream_status=second_stage_obfuscated_thunk; coverage=needs_second_stage_obfuscation_collapse; next_action=decode_downstream_stack_thunk */
    /* followup_classification=obfuscated_native_island; priority=obfuscation_island_candidate; sources=entry_195:1 */
    /* relation_mix=outside_retpatch_window:1; windows=195@0x3655e4:0x779bd-0x77a3d:1 */
    /* note: Source 195 island collapses to 0xc57b8, which begins as another call/stack obfuscation thunk. */
    vm_note_native_obfuscated_island(vm, edge, 0x36afd2u, 0xc57b8u, "stack_obfuscated_island", "second_stage_obfuscated_thunk");
}

void vm_native_obfuscated_island(VMState *vm, uint32_t entry,
                                 const VMNativeObfuscatedIslandEvidence *edge) {
    switch (entry) {
    case 0x23122u:
        obfuscated_island_23122(vm, edge);
        break;
    case 0xe0017u:
        obfuscated_island_e0017(vm, edge);
        break;
    case 0x17bf1fu:
        obfuscated_island_17bf1f(vm, edge);
        break;
    case 0x231586u:
        obfuscated_island_231586(vm, edge);
        break;
    case 0x337d35u:
        obfuscated_island_337d35(vm, edge);
        break;
    case 0x33b4b6u:
        obfuscated_island_33b4b6(vm, edge);
        break;
    case 0x33f109u:
        obfuscated_island_33f109(vm, edge);
        break;
    case 0x36afd2u:
        obfuscated_island_36afd2(vm, edge);
        break;
    default:
        vm_note_native_obfuscated_island(vm, edge, entry, 0, "unknown_obfuscated_entry", "needs_static_audit");
        break;
    }
}
