/*
 * Native obfuscated second-stage slot formula proof.
 *
 * Generated by vm_native_obfuscated_second_stage_slot_proof_dump.c.
 * Capstone validates that each computed jmp [rax] is fed by
 * rax_final = rax_initial + (rbx << 3), with all surrounding immediate
 * add/sub noise canceling to a net zero delta. Dynamic slot evidence is
 * joined from dumps/vmtail-wide-1m-w16/vm_native_obfuscated_second_stage_dynamic.tsv.
 */
#include <stdint.h>

typedef struct VMState {
    uint8_t *ip;
    uint32_t state;
    uint32_t flags;
    uint8_t byte;
} VMState;

typedef struct VMSecondStageSlotProof {
    uint32_t entry;
    uint32_t indirect_jmp_site;
    const char *static_formula;
    const char *dynamic_slot_check;
} VMSecondStageSlotProof;

static void vm_note_second_stage_slot_formula(VMState *vm,
                                                  const VMSecondStageSlotProof *edge,
                                                  uint32_t entry, uint32_t site,
                                                  unsigned index_shift,
                                                  uint64_t net_delta,
                                                  unsigned dynamic_hits,
                                                  const char *static_status,
                                                  const char *proof_status,
                                                  const char *slot_check) {
    (void)vm;
    (void)edge;
    (void)entry;
    (void)site;
    (void)index_shift;
    (void)net_delta;
    (void)dynamic_hits;
    (void)static_status;
    (void)proof_status;
    (void)slot_check;
}

static void second_stage_slot_formula_cad88(VMState *vm, const VMSecondStageSlotProof *edge) {
    /* entry=0xc9849; site=0xcad88; static formula: rax_final=rax_initial+(rbx<<3) */
    /* shift_site=0xcacf1; add_index_site=0xcad3d; jmp_site=0xcad88; pre_delta=0xd96b6a9f; post_delta=0xffffffff26949561; net_delta=0x0 */
    /* dynamic_target_mix=0xbb6e6:1,0x9af18:1,0xb8556:2; slot_entry_mix=323@0xbb6e6:1,169@0x9af18:1,310@0xb8556:2; slot_target_check_mix=slot_index_matches_handler_target:4 */
    vm_note_second_stage_slot_formula(vm, edge, 0xc9849u, 0xcad88u, 3u, 0x0u, 4u, "static_slot_formula_net_zero", "static_dynamic_slot_formula_proven_for_observed_hits", "slot_index_matches_handler_target:4");
}

static void second_stage_slot_formula_cc3f5(VMState *vm, const VMSecondStageSlotProof *edge) {
    /* entry=0xcaf2a; site=0xcc3f5; static formula: rax_final=rax_initial+(rbx<<3) */
    /* shift_site=0xcc36a; add_index_site=0xcc3b0; jmp_site=0xcc3f5; pre_delta=0x1a4afd523; post_delta=0xfffffffe5b502add; net_delta=0x0 */
    /* dynamic_target_mix=0x8a37f:1,0xb8556:1,0x9af18:2; slot_entry_mix=86@0x8a37f:1,310@0xb8556:1,169@0x9af18:2; slot_target_check_mix=slot_index_matches_handler_target:4 */
    vm_note_second_stage_slot_formula(vm, edge, 0xcaf2au, 0xcc3f5u, 3u, 0x0u, 4u, "static_slot_formula_net_zero", "static_dynamic_slot_formula_proven_for_observed_hits", "slot_index_matches_handler_target:4");
}

static void second_stage_slot_formula_c559d(VMState *vm, const VMSecondStageSlotProof *edge) {
    /* entry=0xc4258; site=0xc559d; static formula: rax_final=rax_initial+(rbx<<3) */
    /* shift_site=0xc5512; add_index_site=0xc5558; jmp_site=0xc559d; pre_delta=0x189cc7284; post_delta=0xfffffffe76338d7c; net_delta=0x0 */
    /* dynamic_target_mix=0xbb6e6:1,0x9af18:6,0xb8556:1; slot_entry_mix=323@0xbb6e6:1,169@0x9af18:6,310@0xb8556:1; slot_target_check_mix=slot_index_matches_handler_target:8 */
    vm_note_second_stage_slot_formula(vm, edge, 0xc4258u, 0xc559du, 3u, 0x0u, 8u, "static_slot_formula_net_zero", "static_dynamic_slot_formula_proven_for_observed_hits", "slot_index_matches_handler_target:8");
}

static void second_stage_slot_formula_c6bce(VMState *vm, const VMSecondStageSlotProof *edge) {
    /* entry=0xc57b8; site=0xc6bce; static formula: rax_final=rax_initial+(rbx<<3) */
    /* shift_site=0xc6b43; add_index_site=0xc6b89; jmp_site=0xc6bce; pre_delta=0xffffffffc2ed13b2; post_delta=0x3d12ec4e; net_delta=0x0 */
    /* dynamic_target_mix=0x8a37f:1,0x9af18:2,0xb8556:1; slot_entry_mix=86@0x8a37f:1,169@0x9af18:2,310@0xb8556:1; slot_target_check_mix=slot_index_matches_handler_target:4 */
    vm_note_second_stage_slot_formula(vm, edge, 0xc57b8u, 0xc6bceu, 3u, 0x0u, 4u, "static_slot_formula_net_zero", "static_dynamic_slot_formula_proven_for_observed_hits", "slot_index_matches_handler_target:4");
}

static void second_stage_slot_formula_c80b9(VMState *vm, const VMSecondStageSlotProof *edge) {
    /* entry=0xc6d58; site=0xc80b9; static formula: rax_final=rax_initial+(rbx<<3) */
    /* shift_site=0xc802e; add_index_site=0xc8074; jmp_site=0xc80b9; pre_delta=0x425c7a2f; post_delta=0xffffffffbda385d1; net_delta=0x0 */
    /* dynamic_target_mix=0x8a37f:1,0xb8556:3,0x9af18:4; slot_entry_mix=86@0x8a37f:1,310@0xb8556:3,169@0x9af18:4; slot_target_check_mix=slot_index_matches_handler_target:8 */
    vm_note_second_stage_slot_formula(vm, edge, 0xc6d58u, 0xc80b9u, 3u, 0x0u, 8u, "static_slot_formula_net_zero", "static_dynamic_slot_formula_proven_for_observed_hits", "slot_index_matches_handler_target:8");
}

void vm_native_obfuscated_second_stage_slot_proof(VMState *vm,
                                                   uint32_t indirect_jmp_site,
                                                   const VMSecondStageSlotProof *edge) {
    switch (indirect_jmp_site) {
    case 0xcad88u:
        second_stage_slot_formula_cad88(vm, edge);
        break;
    case 0xcc3f5u:
        second_stage_slot_formula_cc3f5(vm, edge);
        break;
    case 0xc559du:
        second_stage_slot_formula_c559d(vm, edge);
        break;
    case 0xc6bceu:
        second_stage_slot_formula_c6bce(vm, edge);
        break;
    case 0xc80b9u:
        second_stage_slot_formula_c80b9(vm, edge);
        break;
    default:
        vm_note_second_stage_slot_formula(vm, edge, 0, indirect_jmp_site, 0, 0, 0,
                                          "unknown_second_stage_slot_site",
                                          "needs_static_window_analysis", "-");
        break;
    }
}
