/*
 * C-shaped evidence for residual synthetic successor families.
 *
 * This file is generated by vm_unresolved_family_chains_dump.c from the
 * unresolved-family audit, observed-chain slot reconciliation, and native
 * return-patch target atlas. It is intentionally conservative: calls below
 * are evidence records, not hard VM CFG promotions.
 */
#include <stdbool.h>
#include <stdint.h>

typedef struct VMState {
    uint64_t ip;
} VMState;

static void evidence_native_ret_patch(VMState *vm, uint32_t source_entry, uint64_t start_vm_ip, const char *ret_slot, uint64_t native_text_off) {
    (void)vm; (void)source_entry; (void)start_vm_ip; (void)ret_slot; (void)native_text_off;
}

static void evidence_chain_step(VMState *vm, uint64_t chain_start, uint32_t step_index, uint64_t step_vm_ip, uint32_t source_entry, uint32_t first_hop_entry, uint64_t first_hop_vm_ip) {
    (void)vm; (void)chain_start; (void)step_index; (void)step_vm_ip; (void)source_entry; (void)first_hop_entry; (void)first_hop_vm_ip;
}

static void evidence_terminal(VMState *vm, uint64_t terminal_vm_ip, uint32_t terminal_entry) {
    (void)vm; (void)terminal_vm_ip; (void)terminal_entry;
}

static void residual_start_d1445(VMState *vm);
static void residual_start_d5ebc(VMState *vm);
static void residual_start_daf39(VMState *vm);
static void residual_start_122e3c(VMState *vm);
static void residual_start_12906f(VMState *vm);
static void residual_start_17452e(VMState *vm);
static void residual_start_17a420(VMState *vm);
static void residual_start_1a6041(VMState *vm);
static void residual_start_1ed483(VMState *vm);
static void residual_start_2304b8(VMState *vm);
static void residual_start_231b74(VMState *vm);
static void residual_start_333bc9(VMState *vm);
static void residual_start_33710f(VMState *vm);
static void residual_start_33d2d9(VMState *vm);
static void residual_start_3655e4(VMState *vm);

static void residual_start_d1445(VMState *vm) {
    /* family=ufam_02 source_entry=175 start=0xd1445 missing_successor=0xd144b */
    /* transfer_path_hash=bbe0d482f93ad097 branch_unknown=0 ip_expr=0x4 slot_expr_hash=c9fce5d05b97 operands=cb1702008000 footprint=0x6 */
    /* table=table_index_out_of_range offset=0x4388 region=after_dispatch_table runtime_qword=non_pointer_bytes zero_seed=unknown_target */
    /* sampled=sampled_target_match_delta_mismatch sampled_targets=310:1 observed_bridge=sequence_chain_to_focused_direct_bridge next_target=replay_first_indirect_hop_then_promoted_terminal */
    /* native ret-patch kind=single_stack_return ret_seen=yes call_targets=0x206c0:1,0x21a50:1 jump_targets=0x217ff:1,0x21848:1 */
    evidence_native_ret_patch(vm, 175u, 0xd1445ull, "ret1", 0x217cbull);
    /* step_role=residual_chain_step hop_kind=tail slot=0x3d8 table=table_index_out_of_range table_offset=0x4388 reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0xd1445ull, 0u, 0xd1445ull, 175u, 123u, 0xd5eb8ull);
    /* step_role=residual_chain_step hop_kind=tail slot=0x5c0 table=misaligned_or_non_qword_table_read table_offset=0x49bd reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0xd1445ull, 1u, 0xd5ebcull, 195u, 184u, 0xdaf35ull);
    /* step_role=residual_chain_step hop_kind=tail slot=0x5c0 table=misaligned_or_non_qword_table_read table_offset=0x1be reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0xd1445ull, 2u, 0xdaf39ull, 195u, 184u, 0x18c463ull);
    /* step_role=focused_direct_terminal_step hop_kind=dispatch slot=0x150 table=misaligned_or_non_qword_table_read table_offset=0xdf reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0xd1445ull, 3u, 0x18c467ull, 195u, 42u, 0x334a3dull);
    /* dynamic_next source=310 start=0xd4893 end=0xd4897 focused_first_hop_entry=123 focused_first_hop_ip=0xd5eb8 following_residual=0xd5ebc */
    evidence_terminal(vm, 0x334a3dull, 42u);
    /* ret_patch_records=1 observed_chain_steps=4 terminal_block=293 */
}

static void residual_start_d5ebc(VMState *vm) {
    /* family=ufam_03 source_entry=195 start=0xd5ebc missing_successor=0xd5ec2 */
    /* transfer_path_hash=44a20faf942e72a8 branch_unknown=0 ip_expr=0x4 slot_expr_hash=c0ec087b210b operands=1e1e02008000 footprint=0x6 */
    /* table=misaligned_or_non_qword_table_read offset=0x49bd region=after_dispatch_table runtime_qword=non_pointer_bytes zero_seed=unknown_target */
    /* sampled=sequence_only_no_sampled_target_match sampled_targets=310:2,86:1 observed_bridge=sequence_chain_to_focused_direct_bridge next_target=replay_first_indirect_hop_then_promoted_terminal */
    /* native ret-patch kind=single_stack_return ret_seen=yes call_targets=0x206c0:1 jump_targets=0x21e53:1 */
    evidence_native_ret_patch(vm, 195u, 0xd5ebcull, "ret1", 0x21e1eull);
    /* step_role=residual_chain_step hop_kind=tail slot=0x5c0 table=misaligned_or_non_qword_table_read table_offset=0x49bd reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0xd5ebcull, 0u, 0xd5ebcull, 195u, 184u, 0xdaf35ull);
    /* step_role=residual_chain_step hop_kind=tail slot=0x5c0 table=misaligned_or_non_qword_table_read table_offset=0x1be reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0xd5ebcull, 1u, 0xdaf39ull, 195u, 184u, 0x18c463ull);
    /* step_role=focused_direct_terminal_step hop_kind=dispatch slot=0x150 table=misaligned_or_non_qword_table_read table_offset=0xdf reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0xd5ebcull, 2u, 0x18c467ull, 195u, 42u, 0x334a3dull);
    /* dynamic_next source=169 start=0x18bd96 end=0x18bd9a focused_first_hop_entry=184 focused_first_hop_ip=0xdaf35 following_residual=0xdaf39 */
    evidence_terminal(vm, 0x334a3dull, 42u);
    /* ret_patch_records=1 observed_chain_steps=3 terminal_block=293 */
}

static void residual_start_daf39(VMState *vm) {
    /* family=ufam_04 source_entry=195 start=0xdaf39 missing_successor=0xdaf3f */
    /* transfer_path_hash=44a20faf942e72a8 branch_unknown=0 ip_expr=0x4 slot_expr_hash=c0ec087b210b operands=d43002008000 footprint=0x6 */
    /* table=misaligned_or_non_qword_table_read offset=0x1be region=inside_dispatch_table_unaligned runtime_qword=non_pointer_bytes zero_seed=unknown_target */
    /* sampled=sampled_target_match_delta_mismatch sampled_targets=310:2,86:1 observed_bridge=sequence_chain_to_focused_direct_bridge next_target=replay_first_indirect_hop_then_promoted_terminal */
    /* native ret-patch kind=single_stack_return ret_seen=yes call_targets=0x206c0:1,0x23122:1 jump_targets=0x23108:1,0xe0017:1 */
    evidence_native_ret_patch(vm, 195u, 0xdaf39ull, "ret1", 0x230d4ull);
    /* step_role=residual_chain_step hop_kind=tail slot=0x5c0 table=misaligned_or_non_qword_table_read table_offset=0x1be reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0xdaf39ull, 0u, 0xdaf39ull, 195u, 184u, 0x18c463ull);
    /* step_role=focused_direct_terminal_step hop_kind=dispatch slot=0x150 table=misaligned_or_non_qword_table_read table_offset=0xdf reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0xdaf39ull, 1u, 0x18c467ull, 195u, 42u, 0x334a3dull);
    /* dynamic_next source=310 start=0x18c084 end=0x18c088 focused_first_hop_entry=184 focused_first_hop_ip=0x18c463 following_residual=0x18c467 */
    evidence_terminal(vm, 0x334a3dull, 42u);
    /* ret_patch_records=1 observed_chain_steps=2 terminal_block=293 */
}

static void residual_start_122e3c(VMState *vm) {
    /* family=ufam_00 source_entry=299 start=0x122e3c missing_successor=0x122e42 */
    /* transfer_path_hash=b75ed1b046c72a97 branch_unknown=1 ip_expr=0x4 slot_expr_hash=c6f36fb6c762 operands=09d402008000 footprint=0x6 */
    /* table=misaligned_or_non_qword_table_read offset=0xd9cf region=after_dispatch_table runtime_qword=non_pointer_bytes zero_seed=unknown_target */
    /* sampled=sampled_target_match_delta_mismatch sampled_targets=169:1,310:1 observed_bridge=sequence_chain_to_recovered_context_reentry next_target=isolate_context_reentry_first_hop */
    /* native ret-patch kind=single_stack_return ret_seen=yes call_targets=0x206c0:1,0x729b6:1 jump_targets=0x2d440:1,0x2d4c2:1 */
    evidence_native_ret_patch(vm, 299u, 0x122e3cull, "ret1", 0x2d409ull);
    /* step_role=context_reentry_terminal_step hop_kind=tail slot=0x528 table=misaligned_or_non_qword_table_read table_offset=0xd9cf reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0x122e3cull, 0u, 0x122e3cull, 299u, 165u, 0x2c0468ull);
    /* dynamic_next source=169 start=0x2c0464 end=0x2c0468 focused_first_hop_entry=165 focused_first_hop_ip=0x2c0468 following_residual=- */
    evidence_terminal(vm, 0x2c0468ull, 165u);
    /* ret_patch_records=1 observed_chain_steps=1 terminal_block=214 */
}

static void residual_start_12906f(VMState *vm) {
    /* family=ufam_05 source_entry=278 start=0x12906f missing_successor=0x129079 */
    /* transfer_path_hash=bdce1bd00d4b09a0 branch_unknown=0 ip_expr=0x5 slot_expr_hash=4ec538428441 operands=b2b51500800010c00600 footprint=0xa */
    /* table=misaligned_or_non_qword_table_read offset=0xea3c region=after_dispatch_table runtime_qword=non_pointer_bytes zero_seed=unknown_target */
    /* sampled=sequence_only_no_sampled_target_match sampled_targets=323:1,86:1 observed_bridge=sequence_chain_to_recovered_context_reentry next_target=solve_unique_transfer_family */
    /* native ret-patch kind=double_stack_return ret_seen=no call_targets=- jump_targets=0x2d2cf4:1,0x6c0be:1,0x6c064:1 */
    evidence_native_ret_patch(vm, 278u, 0x12906full, "ret1", 0x6c010ull);
    /* native ret-patch kind=double_stack_return ret_seen=no call_targets=- jump_targets=- */
    evidence_native_ret_patch(vm, 278u, 0x12906full, "ret2", 0x15b5b2ull);
    /* step_role=residual_chain_step hop_kind=tail slot=0x3d8 table=misaligned_or_non_qword_table_read table_offset=0xea3c reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0x12906full, 0u, 0x12906full, 278u, 123u, 0x17452aull);
    /* step_role=residual_chain_step hop_kind=tail slot=0x570 table=misaligned_or_non_qword_table_read table_offset=0x8144 reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0x12906full, 1u, 0x17452eull, 299u, 174u, 0x122e38ull);
    /* step_role=context_reentry_terminal_step hop_kind=tail slot=0x528 table=misaligned_or_non_qword_table_read table_offset=0xd9cf reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0x12906full, 2u, 0x122e3cull, 299u, 165u, 0x2c0468ull);
    /* dynamic_next source=310 start=0x172d62 end=0x172d66 focused_first_hop_entry=123 focused_first_hop_ip=0x17452a following_residual=0x17452e */
    evidence_terminal(vm, 0x2c0468ull, 165u);
    /* ret_patch_records=2 observed_chain_steps=3 terminal_block=214 */
}

static void residual_start_17452e(VMState *vm) {
    /* family=ufam_00 source_entry=299 start=0x17452e missing_successor=0x174534 */
    /* transfer_path_hash=b75ed1b046c72a97 branch_unknown=1 ip_expr=0x4 slot_expr_hash=c6f36fb6c762 operands=eb1303008000 footprint=0x6 */
    /* table=misaligned_or_non_qword_table_read offset=0x8144 region=after_dispatch_table runtime_qword=non_pointer_bytes zero_seed=unknown_target */
    /* sampled=sampled_target_match_delta_mismatch sampled_targets=169:1,310:1 observed_bridge=sequence_chain_to_recovered_context_reentry next_target=solve_repeated_central_dispatch_family */
    /* native ret-patch kind=single_stack_return ret_seen=yes call_targets=0x206c0:1 jump_targets=0x31422:1,0x17bf1f:1 */
    evidence_native_ret_patch(vm, 299u, 0x17452eull, "ret1", 0x313ebull);
    /* step_role=residual_chain_step hop_kind=tail slot=0x570 table=misaligned_or_non_qword_table_read table_offset=0x8144 reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0x17452eull, 0u, 0x17452eull, 299u, 174u, 0x122e38ull);
    /* step_role=context_reentry_terminal_step hop_kind=tail slot=0x528 table=misaligned_or_non_qword_table_read table_offset=0xd9cf reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0x17452eull, 1u, 0x122e3cull, 299u, 165u, 0x2c0468ull);
    /* dynamic_next source=310 start=0x2bff9a end=0x2bff9e focused_first_hop_entry=174 focused_first_hop_ip=0x122e38 following_residual=0x122e3c */
    evidence_terminal(vm, 0x2c0468ull, 165u);
    /* ret_patch_records=1 observed_chain_steps=2 terminal_block=214 */
}

static void residual_start_17a420(VMState *vm) {
    /* family=ufam_01 source_entry=175 start=0x17a420 missing_successor=0x17a426 */
    /* transfer_path_hash=bbe0d482f93ad097 branch_unknown=0 ip_expr=0x4 slot_expr_hash=c9fce5d05b97 operands=031703008000 footprint=0x6 */
    /* table=misaligned_or_non_qword_table_read offset=0xc62 region=after_dispatch_table runtime_qword=non_pointer_bytes zero_seed=unknown_target */
    /* sampled=sequence_only_no_sampled_target_match sampled_targets=310:1 observed_bridge=sequence_chain_to_recovered_context_reentry next_target=solve_repeated_central_dispatch_family */
    /* native ret-patch kind=single_stack_return ret_seen=yes call_targets=0x206c0:1,0x48eb2b:1 jump_targets=0x31739:1 */
    evidence_native_ret_patch(vm, 175u, 0x17a420ull, "ret1", 0x31703ull);
    /* step_role=residual_chain_step hop_kind=tail slot=0x570 table=misaligned_or_non_qword_table_read table_offset=0xc62 reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0x17a420ull, 0u, 0x17a420ull, 175u, 174u, 0x231b70ull);
    /* step_role=residual_chain_step hop_kind=tail slot=0x508 table=table_index_out_of_range table_offset=0x69c0 reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0x17a420ull, 1u, 0x231b74ull, 195u, 161u, 0x1ed47full);
    /* step_role=residual_chain_step hop_kind=tail slot=0x570 table=misaligned_or_non_qword_table_read table_offset=0x40be reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0x17a420ull, 2u, 0x1ed483ull, 195u, 174u, 0x1a603dull);
    /* step_role=residual_chain_step hop_kind=tail slot=0x570 table=misaligned_or_non_qword_table_read table_offset=0xe281 reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0x17a420ull, 3u, 0x1a6041ull, 175u, 174u, 0x12906bull);
    /* step_role=residual_chain_step hop_kind=tail slot=0x3d8 table=misaligned_or_non_qword_table_read table_offset=0xea3c reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0x17a420ull, 4u, 0x12906full, 278u, 123u, 0x17452aull);
    /* step_role=residual_chain_step hop_kind=tail slot=0x570 table=misaligned_or_non_qword_table_read table_offset=0x8144 reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0x17a420ull, 5u, 0x17452eull, 299u, 174u, 0x122e38ull);
    /* step_role=context_reentry_terminal_step hop_kind=tail slot=0x528 table=misaligned_or_non_qword_table_read table_offset=0xd9cf reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0x17a420ull, 6u, 0x122e3cull, 299u, 165u, 0x2c0468ull);
    /* dynamic_next source=169 start=0x120afe end=0x120b02 focused_first_hop_entry=174 focused_first_hop_ip=0x231b70 following_residual=0x231b74 */
    evidence_terminal(vm, 0x2c0468ull, 165u);
    /* ret_patch_records=1 observed_chain_steps=7 terminal_block=214 */
}

static void residual_start_1a6041(VMState *vm) {
    /* family=ufam_01 source_entry=175 start=0x1a6041 missing_successor=0x1a6047 */
    /* transfer_path_hash=bbe0d482f93ad097 branch_unknown=0 ip_expr=0x4 slot_expr_hash=c9fce5d05b97 operands=bd3903008000 footprint=0x6 */
    /* table=misaligned_or_non_qword_table_read offset=0xe281 region=after_dispatch_table runtime_qword=non_pointer_bytes zero_seed=unknown_target */
    /* sampled=sequence_only_no_sampled_target_match sampled_targets=310:1 observed_bridge=sequence_chain_to_recovered_context_reentry next_target=solve_repeated_central_dispatch_family */
    /* native ret-patch kind=single_stack_return ret_seen=yes call_targets=0x206c0:1 jump_targets=0x339f0:1 */
    evidence_native_ret_patch(vm, 175u, 0x1a6041ull, "ret1", 0x339bdull);
    /* step_role=residual_chain_step hop_kind=tail slot=0x570 table=misaligned_or_non_qword_table_read table_offset=0xe281 reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0x1a6041ull, 0u, 0x1a6041ull, 175u, 174u, 0x12906bull);
    /* step_role=residual_chain_step hop_kind=tail slot=0x3d8 table=misaligned_or_non_qword_table_read table_offset=0xea3c reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0x1a6041ull, 1u, 0x12906full, 278u, 123u, 0x17452aull);
    /* step_role=residual_chain_step hop_kind=tail slot=0x570 table=misaligned_or_non_qword_table_read table_offset=0x8144 reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0x1a6041ull, 2u, 0x17452eull, 299u, 174u, 0x122e38ull);
    /* step_role=context_reentry_terminal_step hop_kind=tail slot=0x528 table=misaligned_or_non_qword_table_read table_offset=0xd9cf reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0x1a6041ull, 3u, 0x122e3cull, 299u, 165u, 0x2c0468ull);
    /* dynamic_next source=169 start=0x1221a0 end=0x1221a4 focused_first_hop_entry=174 focused_first_hop_ip=0x12906b following_residual=0x12906f */
    evidence_terminal(vm, 0x2c0468ull, 165u);
    /* ret_patch_records=1 observed_chain_steps=4 terminal_block=214 */
}

static void residual_start_1ed483(VMState *vm) {
    /* family=ufam_06 source_entry=195 start=0x1ed483 missing_successor=0x1ed489 */
    /* transfer_path_hash=9917c35930d48ca1 branch_unknown=0 ip_expr=0x4 slot_expr_hash=c0ec087b210b operands=f97a03008000 footprint=0x6 */
    /* table=misaligned_or_non_qword_table_read offset=0x40be region=after_dispatch_table runtime_qword=low32_text_offset zero_seed=unknown_target */
    /* sampled=sampled_target_match_delta_mismatch sampled_targets=310:2,86:1 observed_bridge=sequence_chain_to_recovered_context_reentry next_target=solve_repeated_central_dispatch_family */
    /* native ret-patch kind=single_stack_return ret_seen=yes call_targets=0x206c0:1 jump_targets=0x37b2f:1,0x7260a:1 */
    evidence_native_ret_patch(vm, 195u, 0x1ed483ull, "ret1", 0x37af9ull);
    /* step_role=residual_chain_step hop_kind=tail slot=0x570 table=misaligned_or_non_qword_table_read table_offset=0x40be reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0x1ed483ull, 0u, 0x1ed483ull, 195u, 174u, 0x1a603dull);
    /* step_role=residual_chain_step hop_kind=tail slot=0x570 table=misaligned_or_non_qword_table_read table_offset=0xe281 reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0x1ed483ull, 1u, 0x1a6041ull, 175u, 174u, 0x12906bull);
    /* step_role=residual_chain_step hop_kind=tail slot=0x3d8 table=misaligned_or_non_qword_table_read table_offset=0xea3c reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0x1ed483ull, 2u, 0x12906full, 278u, 123u, 0x17452aull);
    /* step_role=residual_chain_step hop_kind=tail slot=0x570 table=misaligned_or_non_qword_table_read table_offset=0x8144 reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0x1ed483ull, 3u, 0x17452eull, 299u, 174u, 0x122e38ull);
    /* step_role=context_reentry_terminal_step hop_kind=tail slot=0x528 table=misaligned_or_non_qword_table_read table_offset=0xd9cf reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0x1ed483ull, 4u, 0x122e3cull, 299u, 165u, 0x2c0468ull);
    /* dynamic_next source=310 start=0x121ed0 end=0x121ed4 focused_first_hop_entry=174 focused_first_hop_ip=0x1a603d following_residual=0x1a6041 */
    evidence_terminal(vm, 0x2c0468ull, 165u);
    /* ret_patch_records=1 observed_chain_steps=5 terminal_block=214 */
}

static void residual_start_2304b8(VMState *vm) {
    /* family=ufam_07 source_entry=195 start=0x2304b8 missing_successor=0x2304be */
    /* transfer_path_hash=9917c35930d48ca1 branch_unknown=0 ip_expr=0x4 slot_expr_hash=c0ec087b210b operands=7b4d04008000 footprint=0x6 */
    /* table=table_index_out_of_range offset=0x71e0 region=after_dispatch_table runtime_qword=non_pointer_bytes zero_seed=unknown_target */
    /* sampled=sequence_only_no_sampled_target_match sampled_targets=310:2,86:1 observed_bridge=sequence_chain_to_focused_direct_bridge next_target=replay_first_indirect_hop_then_promoted_terminal */
    /* native ret-patch kind=single_stack_return ret_seen=yes call_targets=- jump_targets=0x231586:1 */
    evidence_native_ret_patch(vm, 195u, 0x2304b8ull, "ret1", 0x44d7bull);
    /* step_role=residual_chain_step hop_kind=tail slot=0x4f0 table=table_index_out_of_range table_offset=0x71e0 reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0x2304b8ull, 0u, 0x2304b8ull, 195u, 158u, 0xd1441ull);
    /* step_role=residual_chain_step hop_kind=tail slot=0x3d8 table=table_index_out_of_range table_offset=0x4388 reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0x2304b8ull, 1u, 0xd1445ull, 175u, 123u, 0xd5eb8ull);
    /* step_role=residual_chain_step hop_kind=tail slot=0x5c0 table=misaligned_or_non_qword_table_read table_offset=0x49bd reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0x2304b8ull, 2u, 0xd5ebcull, 195u, 184u, 0xdaf35ull);
    /* step_role=residual_chain_step hop_kind=tail slot=0x5c0 table=misaligned_or_non_qword_table_read table_offset=0x1be reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0x2304b8ull, 3u, 0xdaf39ull, 195u, 184u, 0x18c463ull);
    /* step_role=focused_direct_terminal_step hop_kind=dispatch slot=0x150 table=misaligned_or_non_qword_table_read table_offset=0xdf reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0x2304b8ull, 4u, 0x18c467ull, 195u, 42u, 0x334a3dull);
    /* dynamic_next source=169 start=0xd100c end=0xd1010 focused_first_hop_entry=158 focused_first_hop_ip=0xd1441 following_residual=0xd1445 */
    evidence_terminal(vm, 0x334a3dull, 42u);
    /* ret_patch_records=1 observed_chain_steps=5 terminal_block=293 */
}

static void residual_start_231b74(VMState *vm) {
    /* family=ufam_08 source_entry=195 start=0x231b74 missing_successor=0x231b7a */
    /* transfer_path_hash=44a20faf942e72a8 branch_unknown=0 ip_expr=0x4 slot_expr_hash=c0ec087b210b operands=c6f105008000 footprint=0x6 */
    /* table=table_index_out_of_range offset=0x69c0 region=after_dispatch_table runtime_qword=non_pointer_bytes zero_seed=unknown_target */
    /* sampled=sequence_only_no_sampled_target_match sampled_targets=310:2,86:1 observed_bridge=sequence_chain_to_recovered_context_reentry next_target=solve_repeated_central_dispatch_family */
    /* native ret-patch kind=single_stack_return ret_seen=yes call_targets=0x2508e:2 jump_targets=0x4eeb50:1,0x4eeb30:1,0x5f259:1,0x5f23d:1,0x5f221:1,0x5f24b:1 */
    evidence_native_ret_patch(vm, 195u, 0x231b74ull, "ret1", 0x5f1c6ull);
    /* step_role=residual_chain_step hop_kind=tail slot=0x508 table=table_index_out_of_range table_offset=0x69c0 reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0x231b74ull, 0u, 0x231b74ull, 195u, 161u, 0x1ed47full);
    /* step_role=residual_chain_step hop_kind=tail slot=0x570 table=misaligned_or_non_qword_table_read table_offset=0x40be reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0x231b74ull, 1u, 0x1ed483ull, 195u, 174u, 0x1a603dull);
    /* step_role=residual_chain_step hop_kind=tail slot=0x570 table=misaligned_or_non_qword_table_read table_offset=0xe281 reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0x231b74ull, 2u, 0x1a6041ull, 175u, 174u, 0x12906bull);
    /* step_role=residual_chain_step hop_kind=tail slot=0x3d8 table=misaligned_or_non_qword_table_read table_offset=0xea3c reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0x231b74ull, 3u, 0x12906full, 278u, 123u, 0x17452aull);
    /* step_role=residual_chain_step hop_kind=tail slot=0x570 table=misaligned_or_non_qword_table_read table_offset=0x8144 reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0x231b74ull, 4u, 0x17452eull, 299u, 174u, 0x122e38ull);
    /* step_role=context_reentry_terminal_step hop_kind=tail slot=0x528 table=misaligned_or_non_qword_table_read table_offset=0xd9cf reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0x231b74ull, 5u, 0x122e3cull, 299u, 165u, 0x2c0468ull);
    /* dynamic_next source=169 start=0x121c8d end=0x121c91 focused_first_hop_entry=161 focused_first_hop_ip=0x1ed47f following_residual=0x1ed483 */
    evidence_terminal(vm, 0x2c0468ull, 165u);
    /* ret_patch_records=1 observed_chain_steps=6 terminal_block=214 */
}

static void residual_start_333bc9(VMState *vm) {
    /* family=ufam_09 source_entry=195 start=0x333bc9 missing_successor=0x333bcf */
    /* transfer_path_hash=44a20faf942e72a8 branch_unknown=0 ip_expr=0x4 slot_expr_hash=c0ec087b210b operands=d84807008000 footprint=0x6 */
    /* table=misaligned_or_non_qword_table_read offset=0x48e2 region=after_dispatch_table runtime_qword=non_pointer_bytes zero_seed=unknown_target */
    /* sampled=sequence_only_no_sampled_target_match sampled_targets=310:2,86:1 observed_bridge=sequence_chain_to_focused_direct_bridge next_target=replay_first_indirect_hop_then_promoted_terminal */
    /* native ret-patch kind=single_stack_return ret_seen=yes call_targets=0x206c0:1 jump_targets=0x74910:1,0x337d35:1 */
    evidence_native_ret_patch(vm, 195u, 0x333bc9ull, "ret1", 0x748d8ull);
    /* step_role=residual_chain_step hop_kind=tail slot=0x580 table=misaligned_or_non_qword_table_read table_offset=0x48e2 reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0x333bc9ull, 0u, 0x333bc9ull, 195u, 176u, 0x33a6c8ull);
    /* step_role=focused_direct_terminal_step hop_kind=dispatch slot=0x150 table=misaligned_or_non_qword_table_read table_offset=0x115e reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0x333bc9ull, 1u, 0x33a6ccull, 299u, 42u, 0x33b647ull);
    /* dynamic_next source=169 start=0x31e249 end=0x31e24d focused_first_hop_entry=176 focused_first_hop_ip=0x33a6c8 following_residual=0x33a6cc */
    evidence_terminal(vm, 0x33b647ull, 42u);
    /* ret_patch_records=1 observed_chain_steps=2 terminal_block=324 */
}

static void residual_start_33710f(VMState *vm) {
    /* family=ufam_10 source_entry=299 start=0x33710f missing_successor=0x337115 */
    /* transfer_path_hash=b75ed1b046c72a97 branch_unknown=1 ip_expr=0x4 slot_expr_hash=c6f36fb6c762 operands=3d4b07008000 footprint=0x6 */
    /* table=table_index_out_of_range offset=0x8548 region=after_dispatch_table runtime_qword=non_pointer_bytes zero_seed=unknown_target */
    /* sampled=sampled_target_match_delta_mismatch sampled_targets=169:1,310:1 observed_bridge=sequence_chain_to_focused_direct_bridge next_target=replay_first_indirect_hop_then_promoted_terminal */
    /* native ret-patch kind=single_stack_return ret_seen=yes call_targets=0x206c0:1 jump_targets=0x74b75:1,0x33b4b6:1,0x74c0e:1 */
    evidence_native_ret_patch(vm, 299u, 0x33710full, "ret1", 0x74b3dull);
    /* step_role=residual_chain_step hop_kind=tail slot=0x570 table=table_index_out_of_range table_offset=0x8548 reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0x33710full, 0u, 0x33710full, 299u, 174u, 0x333bc5ull);
    /* step_role=residual_chain_step hop_kind=tail slot=0x580 table=misaligned_or_non_qword_table_read table_offset=0x48e2 reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0x33710full, 1u, 0x333bc9ull, 195u, 176u, 0x33a6c8ull);
    /* step_role=focused_direct_terminal_step hop_kind=dispatch slot=0x150 table=misaligned_or_non_qword_table_read table_offset=0x115e reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0x33710full, 2u, 0x33a6ccull, 299u, 42u, 0x33b647ull);
    /* dynamic_next source=310 start=0x31e05c end=0x31e060 focused_first_hop_entry=174 focused_first_hop_ip=0x333bc5 following_residual=0x333bc9 */
    evidence_terminal(vm, 0x33b647ull, 42u);
    /* ret_patch_records=1 observed_chain_steps=3 terminal_block=324 */
}

static void residual_start_33d2d9(VMState *vm) {
    /* family=ufam_11 source_entry=195 start=0x33d2d9 missing_successor=0x33d2df */
    /* transfer_path_hash=9917c35930d48ca1 branch_unknown=0 ip_expr=0x4 slot_expr_hash=c0ec087b210b operands=884f07008000 footprint=0x6 */
    /* table=misaligned_or_non_qword_table_read offset=0x31e2 region=after_dispatch_table runtime_qword=non_pointer_bytes zero_seed=unknown_target */
    /* sampled=sequence_only_no_sampled_target_match sampled_targets=310:2,86:1 observed_bridge=sequence_chain_to_focused_direct_bridge next_target=replay_first_indirect_hop_then_promoted_terminal */
    /* native ret-patch kind=single_stack_return ret_seen=yes call_targets=0x206c0:1 jump_targets=0x74fbd:1,0x33f109:1 */
    evidence_native_ret_patch(vm, 195u, 0x33d2d9ull, "ret1", 0x74f88ull);
    /* step_role=residual_chain_step hop_kind=tail slot=0x5c0 table=misaligned_or_non_qword_table_read table_offset=0x31e2 reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0x33d2d9ull, 0u, 0x33d2d9ull, 195u, 184u, 0x31f2adull);
    /* step_role=focused_direct_terminal_step hop_kind=dispatch slot=0xa18 table=misaligned_or_non_qword_table_read table_offset=0x68c3 reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0x33d2d9ull, 1u, 0x31f2b1ull, 195u, 323u, 0x33f278ull);
    /* dynamic_next source=169 start=0x31e623 end=0x31e627 focused_first_hop_entry=184 focused_first_hop_ip=0x31f2ad following_residual=0x31f2b1 */
    evidence_terminal(vm, 0x33f278ull, 323u);
    /* ret_patch_records=1 observed_chain_steps=2 terminal_block=340 */
}

static void residual_start_3655e4(VMState *vm) {
    /* family=ufam_12 source_entry=195 start=0x3655e4 missing_successor=0x3655ea */
    /* transfer_path_hash=44a20faf942e72a8 branch_unknown=0 ip_expr=0x4 slot_expr_hash=c0ec087b210b operands=bd7907008000 footprint=0x6 */
    /* table=misaligned_or_non_qword_table_read offset=0x29c3 region=after_dispatch_table runtime_qword=non_pointer_bytes zero_seed=unknown_target */
    /* sampled=sampled_target_match_delta_mismatch sampled_targets=310:2,86:1 observed_bridge=sequence_chain_to_recovered_context_reentry next_target=solve_repeated_central_dispatch_family */
    /* native ret-patch kind=single_stack_return ret_seen=yes call_targets=0x206c0:1 jump_targets=0x779f3:1,0x36afd2:1,0x77a5d:1 */
    evidence_native_ret_patch(vm, 195u, 0x3655e4ull, "ret1", 0x779bdull);
    /* step_role=residual_chain_step hop_kind=tail slot=0x508 table=misaligned_or_non_qword_table_read table_offset=0x29c3 reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0x3655e4ull, 0u, 0x3655e4ull, 195u, 161u, 0x17a41cull);
    /* step_role=residual_chain_step hop_kind=tail slot=0x570 table=misaligned_or_non_qword_table_read table_offset=0xc62 reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0x3655e4ull, 1u, 0x17a420ull, 175u, 174u, 0x231b70ull);
    /* step_role=residual_chain_step hop_kind=tail slot=0x508 table=table_index_out_of_range table_offset=0x69c0 reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0x3655e4ull, 2u, 0x231b74ull, 195u, 161u, 0x1ed47full);
    /* step_role=residual_chain_step hop_kind=tail slot=0x570 table=misaligned_or_non_qword_table_read table_offset=0x40be reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0x3655e4ull, 3u, 0x1ed483ull, 195u, 174u, 0x1a603dull);
    /* step_role=residual_chain_step hop_kind=tail slot=0x570 table=misaligned_or_non_qword_table_read table_offset=0xe281 reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0x3655e4ull, 4u, 0x1a6041ull, 175u, 174u, 0x12906bull);
    /* step_role=residual_chain_step hop_kind=tail slot=0x3d8 table=misaligned_or_non_qword_table_read table_offset=0xea3c reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0x3655e4ull, 5u, 0x12906full, 278u, 123u, 0x17452aull);
    /* step_role=residual_chain_step hop_kind=tail slot=0x570 table=misaligned_or_non_qword_table_read table_offset=0x8144 reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0x3655e4ull, 6u, 0x17452eull, 299u, 174u, 0x122e38ull);
    /* step_role=context_reentry_terminal_step hop_kind=tail slot=0x528 table=misaligned_or_non_qword_table_read table_offset=0xd9cf reconciliation=table_read_rejects_focused_first_hop_as_direct_slot */
    evidence_chain_step(vm, 0x3655e4ull, 7u, 0x122e3cull, 299u, 165u, 0x2c0468ull);
    /* dynamic_next source=310 start=0x11dcff end=0x11dd03 focused_first_hop_entry=161 focused_first_hop_ip=0x17a41c following_residual=0x17a420 */
    evidence_terminal(vm, 0x2c0468ull, 165u);
    /* ret_patch_records=1 observed_chain_steps=8 terminal_block=214 */
}

void vm_unresolved_family_chain_evidence(VMState *vm, uint64_t start_vm_ip) {
    switch (start_vm_ip) {
    case 0xd1445ull:
        residual_start_d1445(vm);
        return;
    case 0xd5ebcull:
        residual_start_d5ebc(vm);
        return;
    case 0xdaf39ull:
        residual_start_daf39(vm);
        return;
    case 0x122e3cull:
        residual_start_122e3c(vm);
        return;
    case 0x12906full:
        residual_start_12906f(vm);
        return;
    case 0x17452eull:
        residual_start_17452e(vm);
        return;
    case 0x17a420ull:
        residual_start_17a420(vm);
        return;
    case 0x1a6041ull:
        residual_start_1a6041(vm);
        return;
    case 0x1ed483ull:
        residual_start_1ed483(vm);
        return;
    case 0x2304b8ull:
        residual_start_2304b8(vm);
        return;
    case 0x231b74ull:
        residual_start_231b74(vm);
        return;
    case 0x333bc9ull:
        residual_start_333bc9(vm);
        return;
    case 0x33710full:
        residual_start_33710f(vm);
        return;
    case 0x33d2d9ull:
        residual_start_33d2d9(vm);
        return;
    case 0x3655e4ull:
        residual_start_3655e4(vm);
        return;
    default:
        return;
    }
}
